// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: annotate_holdings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const holdingIsLive = `-- name: HoldingIsLive :one

SELECT EXISTS(SELECT 1 FROM holdings WHERE id = ?)
`

// Annotation must not invent rows, so every update checks its subject first.
// A retired Holding is still annotatable: correcting the label on something
// put away is exactly the kind of revision annotation is for.
func (q *Queries) HoldingIsLive(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, holdingIsLive, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const uniqueHoldingIsLive = `-- name: UniqueHoldingIsLive :one
SELECT EXISTS(SELECT 1 FROM unique_holdings WHERE holding_id = ?)
`

func (q *Queries) UniqueHoldingIsLive(ctx context.Context, holdingID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, uniqueHoldingIsLive, holdingID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateHoldingExpiry = `-- name: UpdateHoldingExpiry :exec

UPDATE holdings SET expires_on = ? WHERE id = ?
`

type UpdateHoldingExpiryParams struct {
	ExpiresOn sql.NullString
	ID        int64
}

// ANNOTATION for Holding: the three fields that label rather than record.
//
// Everything else about a Holding -- where it is, how much of it there is,
// whether it is out, whether it still exists -- is recorded, because those are
// claims about physical reality and replay must reproduce them. These three are
// not:
//
//	expires_on     what the packet says. A correction is a correction, not a
//	               new fact about the world. It carries no quantity and moves
//	               nothing, so recording it would put a non-event in the
//	               ledger (E7).
//	snoozed_until  a note to the person, about the interface's own nagging.
//	               It has no physical meaning at all.
//	label          which one of several this is. A name, like every other name
//	               in the system.
//
// This file did not exist through v01, so a Holding could not be labelled, its
// printed date corrected, or its nudge silenced -- the same gap
// annotate_locations.sql closed for Locations.
func (q *Queries) UpdateHoldingExpiry(ctx context.Context, arg UpdateHoldingExpiryParams) error {
	_, err := q.db.ExecContext(ctx, updateHoldingExpiry, arg.ExpiresOn, arg.ID)
	return err
}

const updateHoldingSnooze = `-- name: UpdateHoldingSnooze :exec
UPDATE holdings SET snoozed_until = ? WHERE id = ?
`

type UpdateHoldingSnoozeParams struct {
	SnoozedUntil sql.NullString
	ID           int64
}

func (q *Queries) UpdateHoldingSnooze(ctx context.Context, arg UpdateHoldingSnoozeParams) error {
	_, err := q.db.ExecContext(ctx, updateHoldingSnooze, arg.SnoozedUntil, arg.ID)
	return err
}

const updateUniqueHoldingLabel = `-- name: UpdateUniqueHoldingLabel :exec
UPDATE unique_holdings SET label = ? WHERE holding_id = ?
`

type UpdateUniqueHoldingLabelParams struct {
	Label     sql.NullString
	HoldingID int64
}

func (q *Queries) UpdateUniqueHoldingLabel(ctx context.Context, arg UpdateUniqueHoldingLabelParams) error {
	_, err := q.db.ExecContext(ctx, updateUniqueHoldingLabel, arg.Label, arg.HoldingID)
	return err
}
