// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: annotate_categories.sql

package sqlc

import (
	"context"
	"database/sql"
)

const categoryAncestorIDs = `-- name: CategoryAncestorIDs :many

WITH RECURSIVE chain(id, parent_id) AS (
    SELECT categories.id, categories.parent_id FROM categories WHERE categories.id = ?
    UNION ALL
    SELECT c.id, c.parent_id FROM categories c JOIN chain ON c.id = chain.parent_id
)
SELECT id FROM chain LIMIT 256
`

// Cycle guard for C1. Walks ancestors of the prospective new parent and asks
// whether the node being moved is among them. Depth-capped so a corrupt tree
// fails loudly instead of looping forever.
func (q *Queries) CategoryAncestorIDs(ctx context.Context, id int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, categoryAncestorIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const categoryExists = `-- name: CategoryExists :one
SELECT EXISTS(SELECT 1 FROM categories WHERE id = ?)
`

func (q *Queries) CategoryExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, categoryExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countLiveCategoryChildren = `-- name: CountLiveCategoryChildren :one
SELECT count(*) FROM categories WHERE parent_id = ? AND archived_at IS NULL
`

func (q *Queries) CountLiveCategoryChildren(ctx context.Context, parentID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLiveCategoryChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveCategoryItems = `-- name: CountLiveCategoryItems :one
SELECT count(*) FROM items WHERE category_id = ? AND archived_at IS NULL
`

func (q *Queries) CountLiveCategoryItems(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLiveCategoryItems, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCategoryParent = `-- name: GetCategoryParent :one
SELECT parent_id FROM categories WHERE id = ?
`

func (q *Queries) GetCategoryParent(ctx context.Context, id int64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getCategoryParent, id)
	var parent_id sql.NullInt64
	err := row.Scan(&parent_id)
	return parent_id, err
}

const liftCategoryChildren = `-- name: LiftCategoryChildren :exec

UPDATE categories SET parent_id = ? WHERE parent_id = ?
`

type LiftCategoryChildrenParams struct {
	ParentID   sql.NullInt64
	ParentID_2 sql.NullInt64
}

// Archive-with-resolution. Lift is the default because it matches how
// reorganization actually proceeds.
func (q *Queries) LiftCategoryChildren(ctx context.Context, arg LiftCategoryChildrenParams) error {
	_, err := q.db.ExecContext(ctx, liftCategoryChildren, arg.ParentID, arg.ParentID_2)
	return err
}

const liftCategoryItems = `-- name: LiftCategoryItems :exec
UPDATE items SET category_id = ? WHERE category_id = ?
`

type LiftCategoryItemsParams struct {
	CategoryID   int64
	CategoryID_2 int64
}

func (q *Queries) LiftCategoryItems(ctx context.Context, arg LiftCategoryItemsParams) error {
	_, err := q.db.ExecContext(ctx, liftCategoryItems, arg.CategoryID, arg.CategoryID_2)
	return err
}

const setCategoryArchived = `-- name: SetCategoryArchived :exec
UPDATE categories SET archived_at = ? WHERE id = ?
`

type SetCategoryArchivedParams struct {
	ArchivedAt sql.NullString
	ID         int64
}

func (q *Queries) SetCategoryArchived(ctx context.Context, arg SetCategoryArchivedParams) error {
	_, err := q.db.ExecContext(ctx, setCategoryArchived, arg.ArchivedAt, arg.ID)
	return err
}

const updateCategoryDescription = `-- name: UpdateCategoryDescription :exec
UPDATE categories SET description = ? WHERE id = ?
`

type UpdateCategoryDescriptionParams struct {
	Description sql.NullString
	ID          int64
}

func (q *Queries) UpdateCategoryDescription(ctx context.Context, arg UpdateCategoryDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateCategoryDescription, arg.Description, arg.ID)
	return err
}

const updateCategoryName = `-- name: UpdateCategoryName :exec

UPDATE categories SET name = ? WHERE id = ?
`

type UpdateCategoryNameParams struct {
	Name string
	ID   int64
}

// ANNOTATION: revises directly-mutable attributes on rows that already exist.
// No INSERT -- annotation never brings anything into being.
//
// Category's entire mutable surface is annotation, including its parent: it has
// no ledger at all, being a descriptive overlay rather than a model of physical
// reality (schema section 3.1).
func (q *Queries) UpdateCategoryName(ctx context.Context, arg UpdateCategoryNameParams) error {
	_, err := q.db.ExecContext(ctx, updateCategoryName, arg.Name, arg.ID)
	return err
}

const updateCategoryParent = `-- name: UpdateCategoryParent :exec
UPDATE categories SET parent_id = ? WHERE id = ?
`

type UpdateCategoryParentParams struct {
	ParentID sql.NullInt64
	ID       int64
}

func (q *Queries) UpdateCategoryParent(ctx context.Context, arg UpdateCategoryParentParams) error {
	_, err := q.db.ExecContext(ctx, updateCategoryParent, arg.ParentID, arg.ID)
	return err
}
