// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: annotate_items.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countLiveHoldingsOfItem = `-- name: CountLiveHoldingsOfItem :one
SELECT count(*) FROM holdings WHERE item_id = ? AND retired_at IS NULL
`

func (q *Queries) CountLiveHoldingsOfItem(ctx context.Context, itemID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLiveHoldingsOfItem, itemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const setItemArchived = `-- name: SetItemArchived :exec
UPDATE items SET archived_at = ? WHERE id = ?
`

type SetItemArchivedParams struct {
	ArchivedAt sql.NullString
	ID         int64
}

func (q *Queries) SetItemArchived(ctx context.Context, arg SetItemArchivedParams) error {
	_, err := q.db.ExecContext(ctx, setItemArchived, arg.ArchivedAt, arg.ID)
	return err
}

const setItemPlacementConfirmed = `-- name: SetItemPlacementConfirmed :exec
UPDATE items SET placement_confirmed_at = ? WHERE id = ?
`

type SetItemPlacementConfirmedParams struct {
	PlacementConfirmedAt sql.NullString
	ID                   int64
}

func (q *Queries) SetItemPlacementConfirmed(ctx context.Context, arg SetItemPlacementConfirmedParams) error {
	_, err := q.db.ExecContext(ctx, setItemPlacementConfirmed, arg.PlacementConfirmedAt, arg.ID)
	return err
}

const updateItemCategory = `-- name: UpdateItemCategory :exec
UPDATE items SET category_id = ? WHERE id = ?
`

type UpdateItemCategoryParams struct {
	CategoryID int64
	ID         int64
}

func (q *Queries) UpdateItemCategory(ctx context.Context, arg UpdateItemCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateItemCategory, arg.CategoryID, arg.ID)
	return err
}

const updateItemName = `-- name: UpdateItemName :exec

UPDATE items SET name = ? WHERE id = ?
`

type UpdateItemNameParams struct {
	Name string
	ID   int64
}

// ANNOTATION for Item: labels and knowledge only.
//
// Absent by design: kind, content_unit, and package_size. Those TYPE a Holding
// rather than label an Item, so they belong to the ledger (schema section 3.5) and
// changing one is a recorded event, not an edit.
func (q *Queries) UpdateItemName(ctx context.Context, arg UpdateItemNameParams) error {
	_, err := q.db.ExecContext(ctx, updateItemName, arg.Name, arg.ID)
	return err
}

const updateItemNotes = `-- name: UpdateItemNotes :exec
UPDATE items SET notes = ? WHERE id = ?
`

type UpdateItemNotesParams struct {
	Notes sql.NullString
	ID    int64
}

func (q *Queries) UpdateItemNotes(ctx context.Context, arg UpdateItemNotesParams) error {
	_, err := q.db.ExecContext(ctx, updateItemNotes, arg.Notes, arg.ID)
	return err
}
