// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotate_locations.sql

package sqlc

import (
	"context"
	"database/sql"
)

const locationIsLive = `-- name: LocationIsLive :one

SELECT EXISTS(SELECT 1 FROM locations WHERE id = ?)
`

// Annotation must not invent rows, so every update checks its subject first.
// An archived Location is still nameable: correcting the label on something
// put away is exactly the kind of revision annotation is for.
func (q *Queries) LocationIsLive(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, locationIsLive, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateLocationDescription = `-- name: UpdateLocationDescription :exec
UPDATE locations SET description = ? WHERE id = ?
`

type UpdateLocationDescriptionParams struct {
	Description sql.NullString
	ID          int64
}

func (q *Queries) UpdateLocationDescription(ctx context.Context, arg UpdateLocationDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateLocationDescription, arg.Description, arg.ID)
	return err
}

const updateLocationName = `-- name: UpdateLocationName :exec

UPDATE locations SET name = ? WHERE id = ?
`

type UpdateLocationNameParams struct {
	Name string
	ID   int64
}

// ANNOTATION: revises directly-mutable attributes on rows that already exist.
// No INSERT -- annotation never brings anything into being.
//
// A Location's name and description are labels, so they are annotation even
// though everything else about a Location is recorded. Renaming a shelf does
// not move anything, and recording it as an event would make the ledger claim
// otherwise: replay reconstructs containment, and a rename must be invisible
// to that reconstruction.
//
// This file did not exist through v01, which is why a Location could not be
// renamed at all.
func (q *Queries) UpdateLocationName(ctx context.Context, arg UpdateLocationNameParams) error {
	_, err := q.db.ExecContext(ctx, updateLocationName, arg.Name, arg.ID)
	return err
}
