// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger_items.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addUniqueItemVariant = `-- name: AddUniqueItemVariant :exec
INSERT INTO unique_items (item_id, kind) VALUES (?, 'Unique')
`

func (q *Queries) AddUniqueItemVariant(ctx context.Context, itemID int64) error {
	_, err := q.db.ExecContext(ctx, addUniqueItemVariant, itemID)
	return err
}

const countLiveHoldingsOfItemForLedger = `-- name: CountLiveHoldingsOfItemForLedger :one
SELECT count(*) FROM holdings WHERE item_id = ? AND retired_at IS NULL
`

func (q *Queries) CountLiveHoldingsOfItemForLedger(ctx context.Context, itemID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLiveHoldingsOfItemForLedger, itemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBulkItemVariant = `-- name: DeleteBulkItemVariant :exec
DELETE FROM bulk_items WHERE item_id = ?
`

func (q *Queries) DeleteBulkItemVariant(ctx context.Context, itemID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBulkItemVariant, itemID)
	return err
}

const deleteUniqueItemVariant = `-- name: DeleteUniqueItemVariant :exec

DELETE FROM unique_items WHERE item_id = ?
`

// Changing an Item's kind means swapping its variant row: the variant
// references items(id, kind), so the old row must go before the kind changes
// and the new one after.
func (q *Queries) DeleteUniqueItemVariant(ctx context.Context, itemID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUniqueItemVariant, itemID)
	return err
}

const getItemTypingState = `-- name: GetItemTypingState :one
SELECT i.id, i.kind, b.content_unit, b.package_size
FROM items i LEFT JOIN bulk_items b ON b.item_id = i.id
WHERE i.id = ?
`

type GetItemTypingStateRow struct {
	ID          int64
	Kind        string
	ContentUnit sql.NullString
	PackageSize sql.NullInt64
}

func (q *Queries) GetItemTypingState(ctx context.Context, id int64) (GetItemTypingStateRow, error) {
	row := q.db.QueryRowContext(ctx, getItemTypingState, id)
	var i GetItemTypingStateRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ContentUnit,
		&i.PackageSize,
	)
	return i, err
}

const updateBulkItemPackageSize = `-- name: UpdateBulkItemPackageSize :exec
UPDATE bulk_items SET package_size = ? WHERE item_id = ?
`

type UpdateBulkItemPackageSizeParams struct {
	PackageSize sql.NullInt64
	ItemID      int64
}

func (q *Queries) UpdateBulkItemPackageSize(ctx context.Context, arg UpdateBulkItemPackageSizeParams) error {
	_, err := q.db.ExecContext(ctx, updateBulkItemPackageSize, arg.PackageSize, arg.ItemID)
	return err
}

const updateBulkItemUnit = `-- name: UpdateBulkItemUnit :exec
UPDATE bulk_items SET content_unit = ? WHERE item_id = ?
`

type UpdateBulkItemUnitParams struct {
	ContentUnit string
	ItemID      int64
}

func (q *Queries) UpdateBulkItemUnit(ctx context.Context, arg UpdateBulkItemUnitParams) error {
	_, err := q.db.ExecContext(ctx, updateBulkItemUnit, arg.ContentUnit, arg.ItemID)
	return err
}

const updateItemKind = `-- name: UpdateItemKind :exec

UPDATE items SET kind = ? WHERE id = ?
`

type UpdateItemKindParams struct {
	Kind string
	ID   int64
}

// RECORDING for Item: the three attributes that TYPE a Holding.
//
// kind, content_unit, and package_size determine which variant a Holding is,
// which attributes it has, which events are legal against it, and how its
// stored number is read. Changing one is a recorded event, not an edit.
// name and category determine none of those and belong to annotation.
func (q *Queries) UpdateItemKind(ctx context.Context, arg UpdateItemKindParams) error {
	_, err := q.db.ExecContext(ctx, updateItemKind, arg.Kind, arg.ID)
	return err
}
