// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger_holdings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getHoldingProjection = `-- name: GetHoldingProjection :one

SELECT h.id, h.kind, h.stowed_location_id, h.retired_at,
       b.quantity, b.unit_basis,
       u.custody, u.custody_since, u.displaced_to_id
FROM holdings h
LEFT JOIN bulk_holdings b   ON b.holding_id = h.id
LEFT JOIN unique_holdings u ON u.holding_id = h.id
WHERE h.id = ?
`

type GetHoldingProjectionRow struct {
	ID               int64
	Kind             string
	StowedLocationID int64
	RetiredAt        sql.NullString
	Quantity         sql.NullInt64
	UnitBasis        sql.NullString
	Custody          sql.NullString
	CustodySince     sql.NullString
	DisplacedToID    sql.NullInt64
}

// The projection: the ledger-derived attributes, and nothing else. Immutable
// and directly-mutable attributes are absent by construction (K3).
func (q *Queries) GetHoldingProjection(ctx context.Context, id int64) (GetHoldingProjectionRow, error) {
	row := q.db.QueryRowContext(ctx, getHoldingProjection, id)
	var i GetHoldingProjectionRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.StowedLocationID,
		&i.RetiredAt,
		&i.Quantity,
		&i.UnitBasis,
		&i.Custody,
		&i.CustodySince,
		&i.DisplacedToID,
	)
	return i, err
}

const getItemKind = `-- name: GetItemKind :one
SELECT kind FROM items WHERE id = ?
`

func (q *Queries) GetItemKind(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getItemKind, id)
	var kind string
	err := row.Scan(&kind)
	return kind, err
}

const holdingsWithoutCreationEvent = `-- name: HoldingsWithoutCreationEvent :many

SELECT h.id FROM holdings h
WHERE NOT EXISTS (
    SELECT 1 FROM events e
    WHERE e.subject_kind = 'Holding' AND e.subject_id = h.id AND e.type = 'HoldingCreated'
)
`

// H11: every Holding has a creation event. Not declaratively expressible, so it
// is upheld transactionally and checked by this query.
func (q *Queries) HoldingsWithoutCreationEvent(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, holdingsWithoutCreationEvent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBulkHoldingVariant = `-- name: InsertBulkHoldingVariant :exec
INSERT INTO bulk_holdings (holding_id, kind, quantity, unit_basis) VALUES (?, 'Bulk', 0, ?)
`

type InsertBulkHoldingVariantParams struct {
	HoldingID int64
	UnitBasis string
}

func (q *Queries) InsertBulkHoldingVariant(ctx context.Context, arg InsertBulkHoldingVariantParams) error {
	_, err := q.db.ExecContext(ctx, insertBulkHoldingVariant, arg.HoldingID, arg.UnitBasis)
	return err
}

const insertHolding = `-- name: InsertHolding :execlastid

INSERT INTO holdings (item_id, kind, stowed_location_id) VALUES (?, ?, ?)
`

type InsertHoldingParams struct {
	ItemID           int64
	Kind             string
	StowedLocationID int64
}

// RECORDING for Holding: creation, and the projection writes.
//
// Holdings are created HERE rather than in internal/origin because their
// ledger-derived state is VERIFIED. Verification demands a reconstruction
// independent of the state being verified, so creation must be recorded as an
// event -- and stowed_location_id is NOT NULL, so the creating INSERT
// necessarily writes a ledger-derived column (schema section 3.11).
func (q *Queries) InsertHolding(ctx context.Context, arg InsertHoldingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertHolding, arg.ItemID, arg.Kind, arg.StowedLocationID)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertUniqueHoldingVariant = `-- name: InsertUniqueHoldingVariant :exec
INSERT INTO unique_holdings (holding_id, kind, label, custody) VALUES (?, 'Unique', ?, 'AtRest')
`

type InsertUniqueHoldingVariantParams struct {
	HoldingID int64
	Label     sql.NullString
}

func (q *Queries) InsertUniqueHoldingVariant(ctx context.Context, arg InsertUniqueHoldingVariantParams) error {
	_, err := q.db.ExecContext(ctx, insertUniqueHoldingVariant, arg.HoldingID, arg.Label)
	return err
}

const listHoldingIDs = `-- name: ListHoldingIDs :many
SELECT id FROM holdings ORDER BY id
`

func (q *Queries) ListHoldingIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listHoldingIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBulkHoldingProjection = `-- name: UpdateBulkHoldingProjection :exec
UPDATE bulk_holdings SET quantity = ? WHERE holding_id = ?
`

type UpdateBulkHoldingProjectionParams struct {
	Quantity  int64
	HoldingID int64
}

func (q *Queries) UpdateBulkHoldingProjection(ctx context.Context, arg UpdateBulkHoldingProjectionParams) error {
	_, err := q.db.ExecContext(ctx, updateBulkHoldingProjection, arg.Quantity, arg.HoldingID)
	return err
}

const updateHoldingBaseProjection = `-- name: UpdateHoldingBaseProjection :exec
UPDATE holdings SET stowed_location_id = ?, retired_at = ? WHERE id = ?
`

type UpdateHoldingBaseProjectionParams struct {
	StowedLocationID int64
	RetiredAt        sql.NullString
	ID               int64
}

func (q *Queries) UpdateHoldingBaseProjection(ctx context.Context, arg UpdateHoldingBaseProjectionParams) error {
	_, err := q.db.ExecContext(ctx, updateHoldingBaseProjection, arg.StowedLocationID, arg.RetiredAt, arg.ID)
	return err
}

const updateUniqueHoldingProjection = `-- name: UpdateUniqueHoldingProjection :exec
UPDATE unique_holdings SET custody = ?, custody_since = ?, displaced_to_id = ?
WHERE holding_id = ?
`

type UpdateUniqueHoldingProjectionParams struct {
	Custody       string
	CustodySince  sql.NullString
	DisplacedToID sql.NullInt64
	HoldingID     int64
}

func (q *Queries) UpdateUniqueHoldingProjection(ctx context.Context, arg UpdateUniqueHoldingProjectionParams) error {
	_, err := q.db.ExecContext(ctx, updateUniqueHoldingProjection,
		arg.Custody,
		arg.CustodySince,
		arg.DisplacedToID,
		arg.HoldingID,
	)
	return err
}
