// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger_locations.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countLiveLocationChildren = `-- name: CountLiveLocationChildren :one
SELECT count(*) FROM locations WHERE parent_id = ? AND archived_at IS NULL
`

func (q *Queries) CountLiveLocationChildren(ctx context.Context, parentID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLiveLocationChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLocationState = `-- name: GetLocationState :one
SELECT id, parent_id, archived_at FROM locations WHERE id = ?
`

type GetLocationStateRow struct {
	ID         int64
	ParentID   sql.NullInt64
	ArchivedAt sql.NullString
}

func (q *Queries) GetLocationState(ctx context.Context, id int64) (GetLocationStateRow, error) {
	row := q.db.QueryRowContext(ctx, getLocationState, id)
	var i GetLocationStateRow
	err := row.Scan(&i.ID, &i.ParentID, &i.ArchivedAt)
	return i, err
}

const holdingsStowedAt = `-- name: HoldingsStowedAt :many
SELECT id FROM holdings WHERE stowed_location_id = ? AND retired_at IS NULL
`

func (q *Queries) HoldingsStowedAt(ctx context.Context, stowedLocationID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, holdingsStowedAt, stowedLocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLocation = `-- name: InsertLocation :execlastid

INSERT INTO locations (parent_id, name, description) VALUES (?, ?, ?)
`

type InsertLocationParams struct {
	ParentID    sql.NullInt64
	Name        string
	Description sql.NullString
}

// RECORDING for Location.
//
// Location is a model of physical reality that Holdings reference, so its
// structure is ledger-tracked -- unlike Category, which is a descriptive
// overlay with no ledger at all. The ledger boundary falls between them.
//
// The Location ledger exists for COMPLETENESS OF EXPLANATION: re-parenting a
// container moves its contents with no Holding event of their own, so without
// NodeReparented something moved and nothing recorded why. Renaming is absent
// for the same reason it is absent from the boundary: a rename cannot make a
// Holding appear to have moved.
func (q *Queries) InsertLocation(ctx context.Context, arg InsertLocationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertLocation, arg.ParentID, arg.Name, arg.Description)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const liftLocationChildren = `-- name: LiftLocationChildren :exec
UPDATE locations SET parent_id = ? WHERE parent_id = ?
`

type LiftLocationChildrenParams struct {
	ParentID   sql.NullInt64
	ParentID_2 sql.NullInt64
}

func (q *Queries) LiftLocationChildren(ctx context.Context, arg LiftLocationChildrenParams) error {
	_, err := q.db.ExecContext(ctx, liftLocationChildren, arg.ParentID, arg.ParentID_2)
	return err
}

const liveChildLocationIDs = `-- name: LiveChildLocationIDs :many

SELECT id FROM locations
WHERE parent_id = ? AND archived_at IS NULL
ORDER BY id
`

// Live children only. Archiving disposes of what is still there; an already
// archived child was disposed of once and does not move again. The equivalent
// query in query_locations.sql lists all children including archived ones,
// which is right for browsing and wrong for this.
func (q *Queries) LiveChildLocationIDs(ctx context.Context, parentID sql.NullInt64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, liveChildLocationIDs, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationAncestorIDs = `-- name: LocationAncestorIDs :many
WITH RECURSIVE chain(id, parent_id) AS (
    SELECT locations.id, locations.parent_id FROM locations WHERE locations.id = ?
    UNION ALL
    SELECT l.id, l.parent_id FROM locations l JOIN chain ON l.id = chain.parent_id
)
SELECT id FROM chain LIMIT 256
`

func (q *Queries) LocationAncestorIDs(ctx context.Context, id int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, locationAncestorIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationExists = `-- name: LocationExists :one
SELECT EXISTS(SELECT 1 FROM locations WHERE id = ?)
`

func (q *Queries) LocationExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, locationExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const locationsWithoutCreationEvent = `-- name: LocationsWithoutCreationEvent :many

SELECT l.id FROM locations l
WHERE NOT EXISTS (
    SELECT 1 FROM events e
    WHERE e.subject_kind = 'Location' AND e.subject_id = l.id AND e.type = 'NodeCreated'
)
`

// L4: every Location has a creation event.
func (q *Queries) LocationsWithoutCreationEvent(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, locationsWithoutCreationEvent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLocationArchived = `-- name: SetLocationArchived :exec
UPDATE locations SET archived_at = ? WHERE id = ?
`

type SetLocationArchivedParams struct {
	ArchivedAt sql.NullString
	ID         int64
}

func (q *Queries) SetLocationArchived(ctx context.Context, arg SetLocationArchivedParams) error {
	_, err := q.db.ExecContext(ctx, setLocationArchived, arg.ArchivedAt, arg.ID)
	return err
}

const updateLocationParent = `-- name: UpdateLocationParent :exec
UPDATE locations SET parent_id = ? WHERE id = ?
`

type UpdateLocationParentParams struct {
	ParentID sql.NullInt64
	ID       int64
}

func (q *Queries) UpdateLocationParent(ctx context.Context, arg UpdateLocationParentParams) error {
	_, err := q.db.ExecContext(ctx, updateLocationParent, arg.ParentID, arg.ID)
	return err
}
