// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger_events.sql

package sqlc

import (
	"context"
	"database/sql"
)

const acquisitionPayloadsForSubject = `-- name: AcquisitionPayloadsForSubject :many
SELECT p.event_id, p.delta, p.source, p.price
FROM ev_acquisition p JOIN events e ON e.id = p.event_id
WHERE e.subject_kind = 'Holding' AND e.subject_id = ?
`

type AcquisitionPayloadsForSubjectRow struct {
	EventID int64
	Delta   int64
	Source  sql.NullString
	Price   sql.NullInt64
}

func (q *Queries) AcquisitionPayloadsForSubject(ctx context.Context, subjectID int64) ([]AcquisitionPayloadsForSubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, acquisitionPayloadsForSubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcquisitionPayloadsForSubjectRow{}
	for rows.Next() {
		var i AcquisitionPayloadsForSubjectRow
		if err := rows.Scan(
			&i.EventID,
			&i.Delta,
			&i.Source,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCheckpoints = `-- name: CountCheckpoints :one
SELECT count(*) FROM replay_checkpoints
`

func (q *Queries) CountCheckpoints(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCheckpoints)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const custodyPayloadsForSubject = `-- name: CustodyPayloadsForSubject :many
SELECT p.event_id, p.to_custody, p.displaced_to_id
FROM ev_custody p JOIN events e ON e.id = p.event_id
WHERE e.subject_kind = 'Holding' AND e.subject_id = ?
`

type CustodyPayloadsForSubjectRow struct {
	EventID       int64
	ToCustody     string
	DisplacedToID sql.NullInt64
}

func (q *Queries) CustodyPayloadsForSubject(ctx context.Context, subjectID int64) ([]CustodyPayloadsForSubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, custodyPayloadsForSubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustodyPayloadsForSubjectRow{}
	for rows.Next() {
		var i CustodyPayloadsForSubjectRow
		if err := rows.Scan(&i.EventID, &i.ToCustody, &i.DisplacedToID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAllCheckpoints = `-- name: DeleteAllCheckpoints :exec
DELETE FROM replay_checkpoints
`

func (q *Queries) DeleteAllCheckpoints(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllCheckpoints)
	return err
}

const eventsForSubject = `-- name: EventsForSubject :many
SELECT id, subject_kind, subject_id, type, occurred_at, recorded_at, note
FROM events
WHERE subject_kind = ? AND subject_id = ?
ORDER BY id
`

type EventsForSubjectParams struct {
	SubjectKind string
	SubjectID   int64
}

func (q *Queries) EventsForSubject(ctx context.Context, arg EventsForSubjectParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, eventsForSubject, arg.SubjectKind, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SubjectKind,
			&i.SubjectID,
			&i.Type,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsForSubjectAfter = `-- name: EventsForSubjectAfter :many

SELECT id, subject_kind, subject_id, type, occurred_at, recorded_at, note
FROM events
WHERE subject_kind = ? AND subject_id = ? AND id > ?
ORDER BY id
`

type EventsForSubjectAfterParams struct {
	SubjectKind string
	SubjectID   int64
	ID          int64
}

// ------------------------------------------------------------------ replay --
func (q *Queries) EventsForSubjectAfter(ctx context.Context, arg EventsForSubjectAfterParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, eventsForSubjectAfter, arg.SubjectKind, arg.SubjectID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SubjectKind,
			&i.SubjectID,
			&i.Type,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCheckpoint = `-- name: GetCheckpoint :one

SELECT holding_id, through_sequence, as_of, projection
FROM replay_checkpoints WHERE holding_id = ?
`

// ReplayCheckpoint. Freely deletable by design (K2): deleting every checkpoint
// changes performance, never results. Deliberately NOT protected by the
// immutability triggers that guard the ledger itself, because it is rebuildable
// from the ledger and a malformed one costs a rebuild rather than the truth.
func (q *Queries) GetCheckpoint(ctx context.Context, holdingID int64) (ReplayCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, getCheckpoint, holdingID)
	var i ReplayCheckpoint
	err := row.Scan(
		&i.HoldingID,
		&i.ThroughSequence,
		&i.AsOf,
		&i.Projection,
	)
	return i, err
}

const insertAcquisitionPayload = `-- name: InsertAcquisitionPayload :exec
INSERT INTO ev_acquisition (event_id, type, delta, source, price) VALUES (?, ?, ?, ?, ?)
`

type InsertAcquisitionPayloadParams struct {
	EventID int64
	Type    string
	Delta   int64
	Source  sql.NullString
	Price   sql.NullInt64
}

func (q *Queries) InsertAcquisitionPayload(ctx context.Context, arg InsertAcquisitionPayloadParams) error {
	_, err := q.db.ExecContext(ctx, insertAcquisitionPayload,
		arg.EventID,
		arg.Type,
		arg.Delta,
		arg.Source,
		arg.Price,
	)
	return err
}

const insertCustodyPayload = `-- name: InsertCustodyPayload :exec
INSERT INTO ev_custody (event_id, type, to_custody, displaced_to_id) VALUES (?, ?, ?, ?)
`

type InsertCustodyPayloadParams struct {
	EventID       int64
	Type          string
	ToCustody     string
	DisplacedToID sql.NullInt64
}

func (q *Queries) InsertCustodyPayload(ctx context.Context, arg InsertCustodyPayloadParams) error {
	_, err := q.db.ExecContext(ctx, insertCustodyPayload,
		arg.EventID,
		arg.Type,
		arg.ToCustody,
		arg.DisplacedToID,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :execlastid

INSERT INTO events (subject_kind, subject_id, type, occurred_at, recorded_at, note)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	SubjectKind string
	SubjectID   int64
	Type        string
	OccurredAt  string
	RecordedAt  string
	Note        sql.NullString
}

// RECORDING: the ledger. The only writer of ledger-derived columns.
//
// Append is the only write. There is no update and no delete, and the schema
// enforces that with triggers on all 14 ledger tables -- append-only is exactly
// what makes a malformed row permanent, since there is no later write to fix it.
//
// The event and its payload are inserted in the same transaction as the
// projection update. That is O3, and it is what makes H10 a completeness check
// rather than a correctness one.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertEvent,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Type,
		arg.OccurredAt,
		arg.RecordedAt,
		arg.Note,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertNodeCreatedPayload = `-- name: InsertNodeCreatedPayload :exec
INSERT INTO ev_node_created (event_id, type, parent_id) VALUES (?, ?, ?)
`

type InsertNodeCreatedPayloadParams struct {
	EventID  int64
	Type     string
	ParentID sql.NullInt64
}

func (q *Queries) InsertNodeCreatedPayload(ctx context.Context, arg InsertNodeCreatedPayloadParams) error {
	_, err := q.db.ExecContext(ctx, insertNodeCreatedPayload, arg.EventID, arg.Type, arg.ParentID)
	return err
}

const insertNodeLifecyclePayload = `-- name: InsertNodeLifecyclePayload :exec
INSERT INTO ev_node_lifecycle (event_id, type, resolution) VALUES (?, ?, ?)
`

type InsertNodeLifecyclePayloadParams struct {
	EventID    int64
	Type       string
	Resolution sql.NullString
}

func (q *Queries) InsertNodeLifecyclePayload(ctx context.Context, arg InsertNodeLifecyclePayloadParams) error {
	_, err := q.db.ExecContext(ctx, insertNodeLifecyclePayload, arg.EventID, arg.Type, arg.Resolution)
	return err
}

const insertNodeReparentedPayload = `-- name: InsertNodeReparentedPayload :exec
INSERT INTO ev_node_reparented (event_id, type, from_parent_id, to_parent_id) VALUES (?, ?, ?, ?)
`

type InsertNodeReparentedPayloadParams struct {
	EventID      int64
	Type         string
	FromParentID sql.NullInt64
	ToParentID   sql.NullInt64
}

func (q *Queries) InsertNodeReparentedPayload(ctx context.Context, arg InsertNodeReparentedPayloadParams) error {
	_, err := q.db.ExecContext(ctx, insertNodeReparentedPayload,
		arg.EventID,
		arg.Type,
		arg.FromParentID,
		arg.ToParentID,
	)
	return err
}

const insertObservationPayload = `-- name: InsertObservationPayload :exec
INSERT INTO ev_observation (event_id, type, observed_quantity) VALUES (?, ?, ?)
`

type InsertObservationPayloadParams struct {
	EventID          int64
	Type             string
	ObservedQuantity int64
}

func (q *Queries) InsertObservationPayload(ctx context.Context, arg InsertObservationPayloadParams) error {
	_, err := q.db.ExecContext(ctx, insertObservationPayload, arg.EventID, arg.Type, arg.ObservedQuantity)
	return err
}

const insertPackageSizeChangedPayload = `-- name: InsertPackageSizeChangedPayload :exec
INSERT INTO ev_package_size_changed (event_id, type, from_size, to_size) VALUES (?, ?, ?, ?)
`

type InsertPackageSizeChangedPayloadParams struct {
	EventID  int64
	Type     string
	FromSize sql.NullInt64
	ToSize   sql.NullInt64
}

func (q *Queries) InsertPackageSizeChangedPayload(ctx context.Context, arg InsertPackageSizeChangedPayloadParams) error {
	_, err := q.db.ExecContext(ctx, insertPackageSizeChangedPayload,
		arg.EventID,
		arg.Type,
		arg.FromSize,
		arg.ToSize,
	)
	return err
}

const insertPlacementPayload = `-- name: InsertPlacementPayload :exec
INSERT INTO ev_placement (event_id, type, from_location_id, to_location_id) VALUES (?, ?, ?, ?)
`

type InsertPlacementPayloadParams struct {
	EventID        int64
	Type           string
	FromLocationID sql.NullInt64
	ToLocationID   int64
}

func (q *Queries) InsertPlacementPayload(ctx context.Context, arg InsertPlacementPayloadParams) error {
	_, err := q.db.ExecContext(ctx, insertPlacementPayload,
		arg.EventID,
		arg.Type,
		arg.FromLocationID,
		arg.ToLocationID,
	)
	return err
}

const insertPresencePayload = `-- name: InsertPresencePayload :exec
INSERT INTO ev_presence (event_id, type, present) VALUES (?, ?, ?)
`

type InsertPresencePayloadParams struct {
	EventID int64
	Type    string
	Present int64
}

func (q *Queries) InsertPresencePayload(ctx context.Context, arg InsertPresencePayloadParams) error {
	_, err := q.db.ExecContext(ctx, insertPresencePayload, arg.EventID, arg.Type, arg.Present)
	return err
}

const insertQuantityPayload = `-- name: InsertQuantityPayload :exec

INSERT INTO ev_quantity (event_id, type, delta, reason) VALUES (?, ?, ?, ?)
`

type InsertQuantityPayloadParams struct {
	EventID int64
	Type    string
	Delta   int64
	Reason  sql.NullString
}

// ---------------------------------------------------------- payload writes --
func (q *Queries) InsertQuantityPayload(ctx context.Context, arg InsertQuantityPayloadParams) error {
	_, err := q.db.ExecContext(ctx, insertQuantityPayload,
		arg.EventID,
		arg.Type,
		arg.Delta,
		arg.Reason,
	)
	return err
}

const insertTerminalPayload = `-- name: InsertTerminalPayload :exec
INSERT INTO ev_terminal (event_id, type, reason) VALUES (?, ?, ?)
`

type InsertTerminalPayloadParams struct {
	EventID int64
	Type    string
	Reason  sql.NullString
}

func (q *Queries) InsertTerminalPayload(ctx context.Context, arg InsertTerminalPayloadParams) error {
	_, err := q.db.ExecContext(ctx, insertTerminalPayload, arg.EventID, arg.Type, arg.Reason)
	return err
}

const insertUnitChangedPayload = `-- name: InsertUnitChangedPayload :exec
INSERT INTO ev_unit_changed (event_id, type, from_unit, to_unit) VALUES (?, ?, ?, ?)
`

type InsertUnitChangedPayloadParams struct {
	EventID  int64
	Type     string
	FromUnit sql.NullString
	ToUnit   sql.NullString
}

func (q *Queries) InsertUnitChangedPayload(ctx context.Context, arg InsertUnitChangedPayloadParams) error {
	_, err := q.db.ExecContext(ctx, insertUnitChangedPayload,
		arg.EventID,
		arg.Type,
		arg.FromUnit,
		arg.ToUnit,
	)
	return err
}

const latestEventID = `-- name: LatestEventID :one

SELECT id FROM events ORDER BY id DESC LIMIT 1
`

// sqlc cannot type an aggregate like COALESCE(MAX(id), 0) and falls back to
// interface{}, so the sequence head is read as an ordinary row instead.
func (q *Queries) LatestEventID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestEventID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const nodeCreatedPayloadsForSubject = `-- name: NodeCreatedPayloadsForSubject :many
SELECT p.event_id, p.parent_id
FROM ev_node_created p JOIN events e ON e.id = p.event_id
WHERE e.subject_kind = 'Location' AND e.subject_id = ?
`

type NodeCreatedPayloadsForSubjectRow struct {
	EventID  int64
	ParentID sql.NullInt64
}

func (q *Queries) NodeCreatedPayloadsForSubject(ctx context.Context, subjectID int64) ([]NodeCreatedPayloadsForSubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, nodeCreatedPayloadsForSubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeCreatedPayloadsForSubjectRow{}
	for rows.Next() {
		var i NodeCreatedPayloadsForSubjectRow
		if err := rows.Scan(&i.EventID, &i.ParentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeLifecyclePayloadsForSubject = `-- name: NodeLifecyclePayloadsForSubject :many
SELECT p.event_id, p.resolution
FROM ev_node_lifecycle p JOIN events e ON e.id = p.event_id
WHERE e.subject_kind = 'Location' AND e.subject_id = ?
`

type NodeLifecyclePayloadsForSubjectRow struct {
	EventID    int64
	Resolution sql.NullString
}

func (q *Queries) NodeLifecyclePayloadsForSubject(ctx context.Context, subjectID int64) ([]NodeLifecyclePayloadsForSubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, nodeLifecyclePayloadsForSubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeLifecyclePayloadsForSubjectRow{}
	for rows.Next() {
		var i NodeLifecyclePayloadsForSubjectRow
		if err := rows.Scan(&i.EventID, &i.Resolution); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeReparentedPayloadsForSubject = `-- name: NodeReparentedPayloadsForSubject :many
SELECT p.event_id, p.from_parent_id, p.to_parent_id
FROM ev_node_reparented p JOIN events e ON e.id = p.event_id
WHERE e.subject_kind = 'Location' AND e.subject_id = ?
`

type NodeReparentedPayloadsForSubjectRow struct {
	EventID      int64
	FromParentID sql.NullInt64
	ToParentID   sql.NullInt64
}

func (q *Queries) NodeReparentedPayloadsForSubject(ctx context.Context, subjectID int64) ([]NodeReparentedPayloadsForSubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, nodeReparentedPayloadsForSubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeReparentedPayloadsForSubjectRow{}
	for rows.Next() {
		var i NodeReparentedPayloadsForSubjectRow
		if err := rows.Scan(&i.EventID, &i.FromParentID, &i.ToParentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observationPayloadsForSubject = `-- name: ObservationPayloadsForSubject :many
SELECT p.event_id, p.observed_quantity
FROM ev_observation p JOIN events e ON e.id = p.event_id
WHERE e.subject_kind = 'Holding' AND e.subject_id = ?
`

type ObservationPayloadsForSubjectRow struct {
	EventID          int64
	ObservedQuantity int64
}

func (q *Queries) ObservationPayloadsForSubject(ctx context.Context, subjectID int64) ([]ObservationPayloadsForSubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, observationPayloadsForSubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationPayloadsForSubjectRow{}
	for rows.Next() {
		var i ObservationPayloadsForSubjectRow
		if err := rows.Scan(&i.EventID, &i.ObservedQuantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const packageSizeChangedPayloadsForSubject = `-- name: PackageSizeChangedPayloadsForSubject :many
SELECT p.event_id, p.from_size, p.to_size
FROM ev_package_size_changed p JOIN events e ON e.id = p.event_id
WHERE e.subject_kind = 'Item' AND e.subject_id = ?
`

type PackageSizeChangedPayloadsForSubjectRow struct {
	EventID  int64
	FromSize sql.NullInt64
	ToSize   sql.NullInt64
}

func (q *Queries) PackageSizeChangedPayloadsForSubject(ctx context.Context, subjectID int64) ([]PackageSizeChangedPayloadsForSubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, packageSizeChangedPayloadsForSubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackageSizeChangedPayloadsForSubjectRow{}
	for rows.Next() {
		var i PackageSizeChangedPayloadsForSubjectRow
		if err := rows.Scan(&i.EventID, &i.FromSize, &i.ToSize); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const placementPayloadsForSubject = `-- name: PlacementPayloadsForSubject :many
SELECT p.event_id, p.from_location_id, p.to_location_id
FROM ev_placement p JOIN events e ON e.id = p.event_id
WHERE e.subject_kind = 'Holding' AND e.subject_id = ?
`

type PlacementPayloadsForSubjectRow struct {
	EventID        int64
	FromLocationID sql.NullInt64
	ToLocationID   int64
}

func (q *Queries) PlacementPayloadsForSubject(ctx context.Context, subjectID int64) ([]PlacementPayloadsForSubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, placementPayloadsForSubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlacementPayloadsForSubjectRow{}
	for rows.Next() {
		var i PlacementPayloadsForSubjectRow
		if err := rows.Scan(&i.EventID, &i.FromLocationID, &i.ToLocationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const presencePayloadsForSubject = `-- name: PresencePayloadsForSubject :many
SELECT p.event_id, p.present
FROM ev_presence p JOIN events e ON e.id = p.event_id
WHERE e.subject_kind = 'Holding' AND e.subject_id = ?
`

type PresencePayloadsForSubjectRow struct {
	EventID int64
	Present int64
}

func (q *Queries) PresencePayloadsForSubject(ctx context.Context, subjectID int64) ([]PresencePayloadsForSubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, presencePayloadsForSubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresencePayloadsForSubjectRow{}
	for rows.Next() {
		var i PresencePayloadsForSubjectRow
		if err := rows.Scan(&i.EventID, &i.Present); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quantityPayloadsForSubject = `-- name: QuantityPayloadsForSubject :many

SELECT p.event_id, p.delta, p.reason
FROM ev_quantity p JOIN events e ON e.id = p.event_id
WHERE e.subject_kind = 'Holding' AND e.subject_id = ?
`

type QuantityPayloadsForSubjectRow struct {
	EventID int64
	Delta   int64
	Reason  sql.NullString
}

// ----------------------------------------------------------- payload reads --
//
// Scoped by subject rather than by event id, so reading one subject's history
// costs a fixed number of queries regardless of how many events it has.
func (q *Queries) QuantityPayloadsForSubject(ctx context.Context, subjectID int64) ([]QuantityPayloadsForSubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, quantityPayloadsForSubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuantityPayloadsForSubjectRow{}
	for rows.Next() {
		var i QuantityPayloadsForSubjectRow
		if err := rows.Scan(&i.EventID, &i.Delta, &i.Reason); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const terminalPayloadsForSubject = `-- name: TerminalPayloadsForSubject :many
SELECT p.event_id, p.reason
FROM ev_terminal p JOIN events e ON e.id = p.event_id
WHERE e.subject_kind = 'Holding' AND e.subject_id = ?
`

type TerminalPayloadsForSubjectRow struct {
	EventID int64
	Reason  sql.NullString
}

func (q *Queries) TerminalPayloadsForSubject(ctx context.Context, subjectID int64) ([]TerminalPayloadsForSubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, terminalPayloadsForSubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TerminalPayloadsForSubjectRow{}
	for rows.Next() {
		var i TerminalPayloadsForSubjectRow
		if err := rows.Scan(&i.EventID, &i.Reason); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unitChangedPayloadsForSubject = `-- name: UnitChangedPayloadsForSubject :many
SELECT p.event_id, p.from_unit, p.to_unit
FROM ev_unit_changed p JOIN events e ON e.id = p.event_id
WHERE e.subject_kind = 'Item' AND e.subject_id = ?
`

type UnitChangedPayloadsForSubjectRow struct {
	EventID  int64
	FromUnit sql.NullString
	ToUnit   sql.NullString
}

func (q *Queries) UnitChangedPayloadsForSubject(ctx context.Context, subjectID int64) ([]UnitChangedPayloadsForSubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, unitChangedPayloadsForSubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnitChangedPayloadsForSubjectRow{}
	for rows.Next() {
		var i UnitChangedPayloadsForSubjectRow
		if err := rows.Scan(&i.EventID, &i.FromUnit, &i.ToUnit); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCheckpoint = `-- name: UpsertCheckpoint :exec
INSERT INTO replay_checkpoints (holding_id, through_sequence, as_of, projection)
VALUES (?, ?, ?, ?)
ON CONFLICT(holding_id) DO UPDATE SET
    through_sequence = excluded.through_sequence,
    as_of            = excluded.as_of,
    projection       = excluded.projection
`

type UpsertCheckpointParams struct {
	HoldingID       int64
	ThroughSequence int64
	AsOf            string
	Projection      string
}

func (q *Queries) UpsertCheckpoint(ctx context.Context, arg UpsertCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, upsertCheckpoint,
		arg.HoldingID,
		arg.ThroughSequence,
		arg.AsOf,
		arg.Projection,
	)
	return err
}
