// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type BulkHolding struct {
	HoldingID int64
	Kind      string
	Quantity  int64
	UnitBasis string
}

type BulkItem struct {
	ItemID      int64
	Kind        string
	ContentUnit string
	PackageSize sql.NullInt64
}

type Category struct {
	ID          int64
	ParentID    sql.NullInt64
	Name        string
	Description sql.NullString
	CreatedAt   string
	ArchivedAt  sql.NullString
}

type EvAcquisition struct {
	EventID int64
	Type    string
	Delta   int64
	Source  sql.NullString
	Price   sql.NullInt64
}

type EvCustody struct {
	EventID       int64
	Type          string
	ToCustody     string
	DisplacedToID sql.NullInt64
}

type EvNodeCreated struct {
	EventID  int64
	Type     string
	ParentID sql.NullInt64
}

type EvNodeLifecycle struct {
	EventID    int64
	Type       string
	Resolution sql.NullString
}

type EvNodeReparented struct {
	EventID      int64
	Type         string
	FromParentID sql.NullInt64
	ToParentID   sql.NullInt64
}

type EvObservation struct {
	EventID          int64
	Type             string
	ObservedQuantity int64
}

type EvPackageSizeChanged struct {
	EventID  int64
	Type     string
	FromSize sql.NullInt64
	ToSize   sql.NullInt64
}

type EvPlacement struct {
	EventID        int64
	Type           string
	FromLocationID sql.NullInt64
	ToLocationID   int64
}

type EvPresence struct {
	EventID int64
	Type    string
	Present int64
}

type EvQuantity struct {
	EventID int64
	Type    string
	Delta   int64
	Reason  sql.NullString
}

type EvTerminal struct {
	EventID int64
	Type    string
	Reason  sql.NullString
}

type EvUnitChanged struct {
	EventID  int64
	Type     string
	FromUnit sql.NullString
	ToUnit   sql.NullString
}

type Event struct {
	ID          int64
	SubjectKind string
	SubjectID   int64
	Type        string
	OccurredAt  string
	RecordedAt  string
	Note        sql.NullString
}

type Holding struct {
	ID               int64
	ItemID           int64
	Kind             string
	StowedLocationID int64
	ExpiresOn        sql.NullString
	SnoozedUntil     sql.NullString
	RetiredAt        sql.NullString
	CreatedAt        string
}

type Item struct {
	ID                   int64
	Kind                 string
	Name                 string
	CategoryID           int64
	Notes                sql.NullString
	PlacementConfirmedAt sql.NullString
	CreatedAt            string
	ArchivedAt           sql.NullString
}

type Location struct {
	ID          int64
	ParentID    sql.NullInt64
	Name        string
	Description sql.NullString
	CreatedAt   string
	ArchivedAt  sql.NullString
}

type ReplayCheckpoint struct {
	HoldingID       int64
	ThroughSequence int64
	AsOf            string
	Projection      string
}

type SchemaInfo struct {
	ID         int64
	Generation int64
	CreatedAt  string
}

type UniqueHolding struct {
	HoldingID     int64
	Kind          string
	Label         sql.NullString
	Custody       string
	CustodySince  sql.NullString
	DisplacedToID sql.NullInt64
}

type UniqueItem struct {
	ItemID int64
	Kind   string
}

type Unit struct {
	Code         string
	Dimension    string
	ToBaseFactor int64
}
