// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: origin_items.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertBulkItemVariant = `-- name: InsertBulkItemVariant :exec
INSERT INTO bulk_items (item_id, kind, content_unit, package_size)
VALUES (?, 'Bulk', ?, ?)
`

type InsertBulkItemVariantParams struct {
	ItemID      int64
	ContentUnit string
	PackageSize sql.NullInt64
}

func (q *Queries) InsertBulkItemVariant(ctx context.Context, arg InsertBulkItemVariantParams) error {
	_, err := q.db.ExecContext(ctx, insertBulkItemVariant, arg.ItemID, arg.ContentUnit, arg.PackageSize)
	return err
}

const insertItem = `-- name: InsertItem :execlastid

INSERT INTO items (kind, name, category_id, notes) VALUES (?, ?, ?, ?)
`

type InsertItemParams struct {
	Kind       string
	Name       string
	CategoryID int64
	Notes      sql.NullString
}

// ORIGINATION for Item. Base and variant row go in one transaction (O4).
//
// Note that `kind` is a LITERAL in each variant insert rather than a parameter.
// That is what makes a mismatched variant inexpressible through production code
// -- and precisely why these queries cannot prove the database rejects one. That
// proof lives in internal/db/probe.
func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertItem,
		arg.Kind,
		arg.Name,
		arg.CategoryID,
		arg.Notes,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertUniqueItemVariant = `-- name: InsertUniqueItemVariant :exec
INSERT INTO unique_items (item_id, kind) VALUES (?, 'Unique')
`

func (q *Queries) InsertUniqueItemVariant(ctx context.Context, itemID int64) error {
	_, err := q.db.ExecContext(ctx, insertUniqueItemVariant, itemID)
	return err
}
