// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: origin_categories.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertCategory = `-- name: InsertCategory :execlastid

INSERT INTO categories (parent_id, name, description) VALUES (?, ?, ?)
`

type InsertCategoryParams struct {
	ParentID    sql.NullInt64
	Name        string
	Description sql.NullString
}

// ORIGINATION: brings entities into existence and writes their immutable birth
// facts. No UPDATE, no DELETE -- an origination error is permanent, and the only
// remedy is retiring the entity. archlint enforces the absence.
func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertCategory, arg.ParentID, arg.Name, arg.Description)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}
