// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_categories.sql

package sqlc

import (
	"context"
	"database/sql"
)

const categoryDescendants = `-- name: CategoryDescendants :many

WITH RECURSIVE sub(id, parent_id, name, description, created_at, archived_at) AS (
    SELECT categories.id, categories.parent_id, categories.name, categories.description,
           categories.created_at, categories.archived_at
    FROM categories WHERE categories.id = ?
    UNION ALL
    SELECT c.id, c.parent_id, c.name, c.description, c.created_at, c.archived_at
    FROM categories c JOIN sub ON c.parent_id = sub.id
)
SELECT id, parent_id, name, description, created_at, archived_at
FROM sub WHERE archived_at IS NULL LIMIT 4096
`

type CategoryDescendantsRow struct {
	ID          int64
	ParentID    sql.NullInt64
	Name        string
	Description sql.NullString
	CreatedAt   string
	ArchivedAt  sql.NullString
}

// D14/D15: the subtree, which is what lets Items sit at any node without
// breaking any report.
func (q *Queries) CategoryDescendants(ctx context.Context, id int64) ([]CategoryDescendantsRow, error) {
	rows, err := q.db.QueryContext(ctx, categoryDescendants, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryDescendantsRow{}
	for rows.Next() {
		var i CategoryDescendantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const categoryPath = `-- name: CategoryPath :many

WITH RECURSIVE chain(id, parent_id, name, description, created_at, archived_at) AS (
    SELECT categories.id, categories.parent_id, categories.name, categories.description,
           categories.created_at, categories.archived_at
    FROM categories WHERE categories.id = ?
    UNION ALL
    SELECT c.id, c.parent_id, c.name, c.description, c.created_at, c.archived_at
    FROM categories c JOIN chain ON c.id = chain.parent_id
)
SELECT id, parent_id, name, description, created_at, archived_at
FROM chain LIMIT 256
`

type CategoryPathRow struct {
	ID          int64
	ParentID    sql.NullInt64
	Name        string
	Description sql.NullString
	CreatedAt   string
	ArchivedAt  sql.NullString
}

// D13: path, root-first. Renders with PRESENT-DAY names -- history reading
// "Moved to Spice Shelf" tells you where to look today, which is more useful
// than the archaeologically faithful "Moved to Shelf 2".
func (q *Queries) CategoryPath(ctx context.Context, id int64) ([]CategoryPathRow, error) {
	rows, err := q.db.QueryContext(ctx, categoryPath, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryPathRow{}
	for rows.Next() {
		var i CategoryPathRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countItemsInCategoryTree = `-- name: CountItemsInCategoryTree :one
WITH RECURSIVE sub(id) AS (
    SELECT categories.id FROM categories WHERE categories.id = ?
    UNION ALL
    SELECT c.id FROM categories c JOIN sub ON c.parent_id = sub.id
)
SELECT count(*) FROM items
WHERE items.archived_at IS NULL AND items.category_id IN (SELECT id FROM sub)
`

func (q *Queries) CountItemsInCategoryTree(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countItemsInCategoryTree, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCategory = `-- name: GetCategory :one

SELECT id, parent_id, name, description, created_at, archived_at
FROM categories WHERE id = ?
`

// QUERY: reads only. No writes of any kind.
//
// Depth is derived from the parent chain, never stored. The previous system
// stored it and had to maintain it on every re-parent.
//
// Every recursive CTE carries a row LIMIT. C1 is a `checked` invariant upheld at
// write time, so a cycle should be impossible -- but an uncapped recursive query
// against a corrupt tree hangs rather than failing, and a hang is the worst way
// to learn about corruption. The Go layer treats a result that reaches the limit
// as an error, not as a truncated answer.
//
// The CTEs select only base-table columns, and depth is computed in Go. sqlc's
// SQLite analyser cannot type a CTE column with no base-table origin: a computed
// `depth` fails with "column does not exist", and an explicit CAST does not help.
// Confirmed against a minimal reproduction, so it is a tool limitation rather
// than a quirk of these queries.
func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, parent_id, name, description, created_at, archived_at
FROM categories
WHERE archived_at IS NULL
ORDER BY COALESCE(parent_id, 0), name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildCategories = `-- name: ListChildCategories :many
SELECT id, parent_id, name, description, created_at, archived_at
FROM categories
WHERE parent_id = ? AND archived_at IS NULL
ORDER BY name
`

func (q *Queries) ListChildCategories(ctx context.Context, parentID sql.NullInt64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listChildCategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootCategories = `-- name: ListRootCategories :many
SELECT id, parent_id, name, description, created_at, archived_at
FROM categories
WHERE parent_id IS NULL AND archived_at IS NULL
ORDER BY name
`

func (q *Queries) ListRootCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listRootCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
