// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_units.sql

package sqlc

import (
	"context"
)

const getSchemaGeneration = `-- name: GetSchemaGeneration :one
;

SELECT generation FROM schema_info WHERE id =
`

func (q *Queries) GetSchemaGeneration(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSchemaGeneration)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const getUnit = `-- name: GetUnit :one
;

SELECT code, dimension, to_base_factor
FROM units
WHERE code =
`

func (q *Queries) GetUnit(ctx context.Context, code string) (Unit, error) {
	row := q.db.QueryRowContext(ctx, getUnit, code)
	var i Unit
	err := row.Scan(&i.Code, &i.Dimension, &i.ToBaseFactor)
	return i, err
}

const listUnits = `-- name: ListUnits :many

SELECT code, dimension, to_base_factor
FROM units
ORDER BY dimension, to_base_facto
`

// Reference-data reads. Owned by the query path (plan §1.1): no writes.
func (q *Queries) ListUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.QueryContext(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(&i.Code, &i.Dimension, &i.ToBaseFactor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
