// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_locations.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countHoldingsInLocationTree = `-- name: CountHoldingsInLocationTree :one
WITH RECURSIVE sub(id) AS (
    SELECT locations.id FROM locations WHERE locations.id = ?
    UNION ALL
    SELECT l.id FROM locations l JOIN sub ON l.parent_id = sub.id
)
SELECT count(*) FROM holdings
WHERE holdings.retired_at IS NULL AND holdings.stowed_location_id IN (SELECT id FROM sub)
`

func (q *Queries) CountHoldingsInLocationTree(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHoldingsInLocationTree, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLocation = `-- name: GetLocation :one

SELECT id, parent_id, name, description, created_at, archived_at
FROM locations WHERE id = ?
`

// QUERY for Location. Mirrors the Category reads: the tree BEHAVIOUR is one
// abstraction applied twice, even though the entities are deliberately distinct.
//
// Same sqlc constraint as query_categories.sql: recursive CTEs select only
// base-table columns, and depth is derived in Go.
func (q *Queries) GetLocation(ctx context.Context, id int64) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocation, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listChildLocations = `-- name: ListChildLocations :many
SELECT id, parent_id, name, description, created_at, archived_at
FROM locations WHERE parent_id = ? AND archived_at IS NULL ORDER BY name
`

func (q *Queries) ListChildLocations(ctx context.Context, parentID sql.NullInt64) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listChildLocations, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootLocations = `-- name: ListRootLocations :many
SELECT id, parent_id, name, description, created_at, archived_at
FROM locations WHERE parent_id IS NULL AND archived_at IS NULL ORDER BY name
`

func (q *Queries) ListRootLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listRootLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationDescendants = `-- name: LocationDescendants :many
WITH RECURSIVE sub(id, parent_id, name, description, created_at, archived_at) AS (
    SELECT locations.id, locations.parent_id, locations.name, locations.description,
           locations.created_at, locations.archived_at
    FROM locations WHERE locations.id = ?
    UNION ALL
    SELECT l.id, l.parent_id, l.name, l.description, l.created_at, l.archived_at
    FROM locations l JOIN sub ON l.parent_id = sub.id
)
SELECT id, parent_id, name, description, created_at, archived_at
FROM sub WHERE archived_at IS NULL LIMIT 4096
`

type LocationDescendantsRow struct {
	ID          int64
	ParentID    sql.NullInt64
	Name        string
	Description sql.NullString
	CreatedAt   string
	ArchivedAt  sql.NullString
}

func (q *Queries) LocationDescendants(ctx context.Context, id int64) ([]LocationDescendantsRow, error) {
	rows, err := q.db.QueryContext(ctx, locationDescendants, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LocationDescendantsRow{}
	for rows.Next() {
		var i LocationDescendantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationPath = `-- name: LocationPath :many
WITH RECURSIVE chain(id, parent_id, name, description, created_at, archived_at) AS (
    SELECT locations.id, locations.parent_id, locations.name, locations.description,
           locations.created_at, locations.archived_at
    FROM locations WHERE locations.id = ?
    UNION ALL
    SELECT l.id, l.parent_id, l.name, l.description, l.created_at, l.archived_at
    FROM locations l JOIN chain ON l.id = chain.parent_id
)
SELECT id, parent_id, name, description, created_at, archived_at FROM chain LIMIT 256
`

type LocationPathRow struct {
	ID          int64
	ParentID    sql.NullInt64
	Name        string
	Description sql.NullString
	CreatedAt   string
	ArchivedAt  sql.NullString
}

func (q *Queries) LocationPath(ctx context.Context, id int64) ([]LocationPathRow, error) {
	rows, err := q.db.QueryContext(ctx, locationPath, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LocationPathRow{}
	for rows.Next() {
		var i LocationPathRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
