// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_holdings.sql

package sqlc

import (
	"context"
)

const bulkOnHand = `-- name: BulkOnHand :one

SELECT COALESCE(SUM(
    CASE WHEN b.unit_basis = 'Package'
         THEN (b.quantity * COALESCE(bi.package_size, 0)) / 1000
         ELSE b.quantity END
), 0) AS on_hand_milli
FROM holdings h
JOIN bulk_holdings b ON b.holding_id = h.id
LEFT JOIN bulk_items bi ON bi.item_id = h.item_id
WHERE h.item_id = ? AND h.retired_at IS NULL
`

// D7: on-hand for a Bulk item, summed in content units across live holdings.
//
// A Package-basis holding contributes quantity x package_size, and BOTH are in
// milli-units -- so the product is milli-squared and has to be divided by the
// scale. Getting this wrong reports a thousand times too much, which is the
// standing hazard of scaled-integer arithmetic and the reason the scale is
// named rather than written as a literal in Go.
func (q *Queries) BulkOnHand(ctx context.Context, itemID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, bulkOnHand, itemID)
	var on_hand_milli interface{}
	err := row.Scan(&on_hand_milli)
	return on_hand_milli, err
}

const getHoldingWithDetail = `-- name: GetHoldingWithDetail :one
SELECT id, item_id, kind, stowed_location_id, expires_on, snoozed_until, retired_at, created_at, item_name, location_name, quantity, unit_basis, content_unit, package_size, label, custody, custody_since, displaced_to_id FROM holdings_with_detail
WHERE id = ?
`

func (q *Queries) GetHoldingWithDetail(ctx context.Context, id int64) (HoldingsWithDetail, error) {
	row := q.db.QueryRowContext(ctx, getHoldingWithDetail, id)
	var i HoldingsWithDetail
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Kind,
		&i.StowedLocationID,
		&i.ExpiresOn,
		&i.SnoozedUntil,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.ItemName,
		&i.LocationName,
		&i.Quantity,
		&i.UnitBasis,
		&i.ContentUnit,
		&i.PackageSize,
		&i.Label,
		&i.Custody,
		&i.CustodySince,
		&i.DisplacedToID,
	)
	return i, err
}

const holdingsOfItemWithDetail = `-- name: HoldingsOfItemWithDetail :many

SELECT id, item_id, kind, stowed_location_id, expires_on, snoozed_until, retired_at, created_at, item_name, location_name, quantity, unit_basis, content_unit, package_size, label, custody, custody_since, displaced_to_id FROM holdings_with_detail
WHERE item_id = ? AND retired_at IS NULL
ORDER BY id
`

// Every live Holding of one Item, wherever it is kept. This is what the
// composing operations plan against: consuming from a bag has to know which
// holdings exist at the location, in which unit basis, before it can decide
// whether a package must be opened.
func (q *Queries) HoldingsOfItemWithDetail(ctx context.Context, itemID int64) ([]HoldingsWithDetail, error) {
	rows, err := q.db.QueryContext(ctx, holdingsOfItemWithDetail, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HoldingsWithDetail{}
	for rows.Next() {
		var i HoldingsWithDetail
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Kind,
			&i.StowedLocationID,
			&i.ExpiresOn,
			&i.SnoozedUntil,
			&i.RetiredAt,
			&i.CreatedAt,
			&i.ItemName,
			&i.LocationName,
			&i.Quantity,
			&i.UnitBasis,
			&i.ContentUnit,
			&i.PackageSize,
			&i.Label,
			&i.Custody,
			&i.CustodySince,
			&i.DisplacedToID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoldingsWithDetail = `-- name: ListHoldingsWithDetail :many

SELECT id, item_id, kind, stowed_location_id, expires_on, snoozed_until, retired_at, created_at, item_name, location_name, quantity, unit_basis, content_unit, package_size, label, custody, custody_since, displaced_to_id FROM holdings_with_detail
ORDER BY item_name, id
`

// QUERY for Holding. The join a display needs is the holdings_with_detail view,
// defined once in 0007 -- these three queries differ only in what they select
// FROM it, which is the whole of what actually differs between them.
func (q *Queries) ListHoldingsWithDetail(ctx context.Context) ([]HoldingsWithDetail, error) {
	rows, err := q.db.QueryContext(ctx, listHoldingsWithDetail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HoldingsWithDetail{}
	for rows.Next() {
		var i HoldingsWithDetail
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Kind,
			&i.StowedLocationID,
			&i.ExpiresOn,
			&i.SnoozedUntil,
			&i.RetiredAt,
			&i.CreatedAt,
			&i.ItemName,
			&i.LocationName,
			&i.Quantity,
			&i.UnitBasis,
			&i.ContentUnit,
			&i.PackageSize,
			&i.Label,
			&i.Custody,
			&i.CustodySince,
			&i.DisplacedToID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uniqueOnHand = `-- name: UniqueOnHand :one

SELECT count(*) FROM holdings WHERE item_id = ? AND retired_at IS NULL
`

// D7 for Unique items is a different formula entirely: a COUNT of live
// holdings, not a sum. That asymmetry is why on_hand dispatches on kind.
func (q *Queries) UniqueOnHand(ctx context.Context, itemID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, uniqueOnHand, itemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
