// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_holdings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const bulkOnHand = `-- name: BulkOnHand :one

SELECT COALESCE(SUM(
    CASE WHEN b.unit_basis = 'Package'
         THEN (b.quantity * COALESCE(bi.package_size, 0)) / 1000
         ELSE b.quantity END
), 0) AS on_hand_milli
FROM holdings h
JOIN bulk_holdings b ON b.holding_id = h.id
LEFT JOIN bulk_items bi ON bi.item_id = h.item_id
WHERE h.item_id = ? AND h.retired_at IS NULL
`

// D7: on-hand for a Bulk item, summed in content units across live holdings.
//
// A Package-basis holding contributes quantity x package_size, and BOTH are in
// milli-units -- so the product is milli-squared and has to be divided by the
// scale. Getting this wrong reports a thousand times too much, which is the
// standing hazard of scaled-integer arithmetic and the reason the scale is
// named rather than written as a literal in Go.
func (q *Queries) BulkOnHand(ctx context.Context, itemID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, bulkOnHand, itemID)
	var on_hand_milli interface{}
	err := row.Scan(&on_hand_milli)
	return on_hand_milli, err
}

const getHoldingWithDetail = `-- name: GetHoldingWithDetail :one
SELECT
    h.id, h.item_id, h.kind, h.stowed_location_id,
    h.expires_on, h.snoozed_until, h.retired_at, h.created_at,
    i.name AS item_name,
    l.name AS location_name,
    b.quantity, b.unit_basis,
    bi.content_unit, bi.package_size,
    u.label, u.custody, u.custody_since, u.displaced_to_id
FROM holdings h
JOIN items i ON i.id = h.item_id
JOIN locations l ON l.id = h.stowed_location_id
LEFT JOIN bulk_holdings b   ON b.holding_id = h.id
LEFT JOIN bulk_items bi     ON bi.item_id = h.item_id
LEFT JOIN unique_holdings u ON u.holding_id = h.id
WHERE h.id = ?
`

type GetHoldingWithDetailRow struct {
	ID               int64
	ItemID           int64
	Kind             string
	StowedLocationID int64
	ExpiresOn        sql.NullString
	SnoozedUntil     sql.NullString
	RetiredAt        sql.NullString
	CreatedAt        string
	ItemName         string
	LocationName     string
	Quantity         sql.NullInt64
	UnitBasis        sql.NullString
	ContentUnit      sql.NullString
	PackageSize      sql.NullInt64
	Label            sql.NullString
	Custody          sql.NullString
	CustodySince     sql.NullString
	DisplacedToID    sql.NullInt64
}

func (q *Queries) GetHoldingWithDetail(ctx context.Context, id int64) (GetHoldingWithDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getHoldingWithDetail, id)
	var i GetHoldingWithDetailRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Kind,
		&i.StowedLocationID,
		&i.ExpiresOn,
		&i.SnoozedUntil,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.ItemName,
		&i.LocationName,
		&i.Quantity,
		&i.UnitBasis,
		&i.ContentUnit,
		&i.PackageSize,
		&i.Label,
		&i.Custody,
		&i.CustodySince,
		&i.DisplacedToID,
	)
	return i, err
}

const holdingsOfItemWithDetail = `-- name: HoldingsOfItemWithDetail :many

SELECT
    h.id, h.item_id, h.kind, h.stowed_location_id,
    h.expires_on, h.snoozed_until, h.retired_at, h.created_at,
    i.name AS item_name,
    l.name AS location_name,
    b.quantity, b.unit_basis,
    bi.content_unit, bi.package_size,
    u.label, u.custody, u.custody_since, u.displaced_to_id
FROM holdings h
JOIN items i ON i.id = h.item_id
JOIN locations l ON l.id = h.stowed_location_id
LEFT JOIN bulk_holdings b   ON b.holding_id = h.id
LEFT JOIN bulk_items bi     ON bi.item_id = h.item_id
LEFT JOIN unique_holdings u ON u.holding_id = h.id
WHERE h.item_id = ? AND h.retired_at IS NULL
ORDER BY h.id
`

type HoldingsOfItemWithDetailRow struct {
	ID               int64
	ItemID           int64
	Kind             string
	StowedLocationID int64
	ExpiresOn        sql.NullString
	SnoozedUntil     sql.NullString
	RetiredAt        sql.NullString
	CreatedAt        string
	ItemName         string
	LocationName     string
	Quantity         sql.NullInt64
	UnitBasis        sql.NullString
	ContentUnit      sql.NullString
	PackageSize      sql.NullInt64
	Label            sql.NullString
	Custody          sql.NullString
	CustodySince     sql.NullString
	DisplacedToID    sql.NullInt64
}

// Every live Holding of one Item, wherever it is kept. This is what the
// composing operations plan against: consuming from a bag has to know which
// holdings exist at the location, in which unit basis, before it can decide
// whether a package must be opened.
func (q *Queries) HoldingsOfItemWithDetail(ctx context.Context, itemID int64) ([]HoldingsOfItemWithDetailRow, error) {
	rows, err := q.db.QueryContext(ctx, holdingsOfItemWithDetail, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HoldingsOfItemWithDetailRow{}
	for rows.Next() {
		var i HoldingsOfItemWithDetailRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Kind,
			&i.StowedLocationID,
			&i.ExpiresOn,
			&i.SnoozedUntil,
			&i.RetiredAt,
			&i.CreatedAt,
			&i.ItemName,
			&i.LocationName,
			&i.Quantity,
			&i.UnitBasis,
			&i.ContentUnit,
			&i.PackageSize,
			&i.Label,
			&i.Custody,
			&i.CustodySince,
			&i.DisplacedToID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoldingsWithDetail = `-- name: ListHoldingsWithDetail :many

SELECT
    h.id, h.item_id, h.kind, h.stowed_location_id,
    h.expires_on, h.snoozed_until, h.retired_at, h.created_at,
    i.name AS item_name,
    l.name AS location_name,
    b.quantity, b.unit_basis,
    bi.content_unit, bi.package_size,
    u.label, u.custody, u.custody_since, u.displaced_to_id
FROM holdings h
JOIN items i ON i.id = h.item_id
JOIN locations l ON l.id = h.stowed_location_id
LEFT JOIN bulk_holdings b   ON b.holding_id = h.id
LEFT JOIN bulk_items bi     ON bi.item_id = h.item_id
LEFT JOIN unique_holdings u ON u.holding_id = h.id
ORDER BY i.name, h.id
`

type ListHoldingsWithDetailRow struct {
	ID               int64
	ItemID           int64
	Kind             string
	StowedLocationID int64
	ExpiresOn        sql.NullString
	SnoozedUntil     sql.NullString
	RetiredAt        sql.NullString
	CreatedAt        string
	ItemName         string
	LocationName     string
	Quantity         sql.NullInt64
	UnitBasis        sql.NullString
	ContentUnit      sql.NullString
	PackageSize      sql.NullInt64
	Label            sql.NullString
	Custody          sql.NullString
	CustodySince     sql.NullString
	DisplacedToID    sql.NullInt64
}

// QUERY for Holding, joining everything a display needs in one pass.
//
// Both variant tables are joined so the Go layer can hydrate the right one and
// surface the checked half of H5: "at least one variant row" cannot be expressed
// declaratively, so a kind with no matching row must fail loudly here rather
// than as a nil dereference downstream.
func (q *Queries) ListHoldingsWithDetail(ctx context.Context) ([]ListHoldingsWithDetailRow, error) {
	rows, err := q.db.QueryContext(ctx, listHoldingsWithDetail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHoldingsWithDetailRow{}
	for rows.Next() {
		var i ListHoldingsWithDetailRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Kind,
			&i.StowedLocationID,
			&i.ExpiresOn,
			&i.SnoozedUntil,
			&i.RetiredAt,
			&i.CreatedAt,
			&i.ItemName,
			&i.LocationName,
			&i.Quantity,
			&i.UnitBasis,
			&i.ContentUnit,
			&i.PackageSize,
			&i.Label,
			&i.Custody,
			&i.CustodySince,
			&i.DisplacedToID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uniqueOnHand = `-- name: UniqueOnHand :one

SELECT count(*) FROM holdings WHERE item_id = ? AND retired_at IS NULL
`

// D7 for Unique items is a different formula entirely: a COUNT of live
// holdings, not a sum. That asymmetry is why on_hand dispatches on kind.
func (q *Queries) UniqueOnHand(ctx context.Context, itemID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, uniqueOnHand, itemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
