// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_items.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getItemWithVariant = `-- name: GetItemWithVariant :one

SELECT
    i.id, i.kind, i.name, i.category_id, i.notes,
    i.placement_confirmed_at, i.created_at, i.archived_at,
    u.item_id AS unique_variant_id,
    b.item_id AS bulk_variant_id,
    b.content_unit, b.package_size
FROM items i
LEFT JOIN unique_items u ON u.item_id = i.id
LEFT JOIN bulk_items   b ON b.item_id = i.id
WHERE i.id = ?
`

type GetItemWithVariantRow struct {
	ID                   int64
	Kind                 string
	Name                 string
	CategoryID           int64
	Notes                sql.NullString
	PlacementConfirmedAt sql.NullString
	CreatedAt            string
	ArchivedAt           sql.NullString
	UniqueVariantID      sql.NullInt64
	BulkVariantID        sql.NullInt64
	ContentUnit          sql.NullString
	PackageSize          sql.NullInt64
}

// QUERY for Item, hydrating the correct variant.
//
// Both variant tables are joined so the Go layer can check I3's remaining half:
// "at least one variant row exists" is a CHECKED invariant -- the primary key
// gives "at most one" declaratively, but nothing declarative can require one.
// A kind with no matching variant row surfaces here rather than as a nil deref
// somewhere downstream.
func (q *Queries) GetItemWithVariant(ctx context.Context, id int64) (GetItemWithVariantRow, error) {
	row := q.db.QueryRowContext(ctx, getItemWithVariant, id)
	var i GetItemWithVariantRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.CategoryID,
		&i.Notes,
		&i.PlacementConfirmedAt,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.UniqueVariantID,
		&i.BulkVariantID,
		&i.ContentUnit,
		&i.PackageSize,
	)
	return i, err
}

const listItemsInCategoryWithVariant = `-- name: ListItemsInCategoryWithVariant :many
SELECT
    i.id, i.kind, i.name, i.category_id, i.notes,
    i.placement_confirmed_at, i.created_at, i.archived_at,
    u.item_id AS unique_variant_id,
    b.item_id AS bulk_variant_id,
    b.content_unit, b.package_size
FROM items i
LEFT JOIN unique_items u ON u.item_id = i.id
LEFT JOIN bulk_items   b ON b.item_id = i.id
WHERE i.category_id = ? AND i.archived_at IS NULL
ORDER BY i.name
`

type ListItemsInCategoryWithVariantRow struct {
	ID                   int64
	Kind                 string
	Name                 string
	CategoryID           int64
	Notes                sql.NullString
	PlacementConfirmedAt sql.NullString
	CreatedAt            string
	ArchivedAt           sql.NullString
	UniqueVariantID      sql.NullInt64
	BulkVariantID        sql.NullInt64
	ContentUnit          sql.NullString
	PackageSize          sql.NullInt64
}

func (q *Queries) ListItemsInCategoryWithVariant(ctx context.Context, categoryID int64) ([]ListItemsInCategoryWithVariantRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemsInCategoryWithVariant, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsInCategoryWithVariantRow{}
	for rows.Next() {
		var i ListItemsInCategoryWithVariantRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.CategoryID,
			&i.Notes,
			&i.PlacementConfirmedAt,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.UniqueVariantID,
			&i.BulkVariantID,
			&i.ContentUnit,
			&i.PackageSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsWithVariant = `-- name: ListItemsWithVariant :many
SELECT
    i.id, i.kind, i.name, i.category_id, i.notes,
    i.placement_confirmed_at, i.created_at, i.archived_at,
    u.item_id AS unique_variant_id,
    b.item_id AS bulk_variant_id,
    b.content_unit, b.package_size
FROM items i
LEFT JOIN unique_items u ON u.item_id = i.id
LEFT JOIN bulk_items   b ON b.item_id = i.id
WHERE i.archived_at IS NULL
ORDER BY i.name
`

type ListItemsWithVariantRow struct {
	ID                   int64
	Kind                 string
	Name                 string
	CategoryID           int64
	Notes                sql.NullString
	PlacementConfirmedAt sql.NullString
	CreatedAt            string
	ArchivedAt           sql.NullString
	UniqueVariantID      sql.NullInt64
	BulkVariantID        sql.NullInt64
	ContentUnit          sql.NullString
	PackageSize          sql.NullInt64
}

func (q *Queries) ListItemsWithVariant(ctx context.Context) ([]ListItemsWithVariantRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemsWithVariant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsWithVariantRow{}
	for rows.Next() {
		var i ListItemsWithVariantRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.CategoryID,
			&i.Notes,
			&i.PlacementConfirmedAt,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.UniqueVariantID,
			&i.BulkVariantID,
			&i.ContentUnit,
			&i.PackageSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnconfirmedItemsAtBranchCategories = `-- name: ListUnconfirmedItemsAtBranchCategories :many

SELECT
    i.id, i.name, i.category_id, c.name AS category_name,
    (SELECT count(*) FROM categories ch WHERE ch.parent_id = c.id AND ch.archived_at IS NULL) AS child_count
FROM items i
JOIN categories c ON c.id = i.category_id
WHERE i.archived_at IS NULL
  AND i.placement_confirmed_at IS NULL
  AND (SELECT count(*) FROM categories ch WHERE ch.parent_id = c.id AND ch.archived_at IS NULL) > 0
ORDER BY c.name, i.name
`

type ListUnconfirmedItemsAtBranchCategoriesRow struct {
	ID           int64
	Name         string
	CategoryID   int64
	CategoryName string
	ChildCount   int64
}

// D20's raw material: Items filed directly at a Category that has children, and
// whose placement has not been confirmed. The nudge fires only where a plausible
// sibling exists, which is why the child count matters.
func (q *Queries) ListUnconfirmedItemsAtBranchCategories(ctx context.Context) ([]ListUnconfirmedItemsAtBranchCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnconfirmedItemsAtBranchCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnconfirmedItemsAtBranchCategoriesRow{}
	for rows.Next() {
		var i ListUnconfirmedItemsAtBranchCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.CategoryName,
			&i.ChildCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
