// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_items.sql

package sqlc

import (
	"context"
)

const getItemWithVariant = `-- name: GetItemWithVariant :one

SELECT id, kind, name, category_id, notes, placement_confirmed_at, created_at, archived_at, unique_variant_id, bulk_variant_id, content_unit, package_size FROM items_with_variant
WHERE id = ?
`

// QUERY for Item. The variant join is the items_with_variant view, defined once
// in 0007 -- these queries differ only in what they select FROM it.
func (q *Queries) GetItemWithVariant(ctx context.Context, id int64) (ItemsWithVariant, error) {
	row := q.db.QueryRowContext(ctx, getItemWithVariant, id)
	var i ItemsWithVariant
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.CategoryID,
		&i.Notes,
		&i.PlacementConfirmedAt,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.UniqueVariantID,
		&i.BulkVariantID,
		&i.ContentUnit,
		&i.PackageSize,
	)
	return i, err
}

const listItemsInCategoryWithVariant = `-- name: ListItemsInCategoryWithVariant :many
SELECT id, kind, name, category_id, notes, placement_confirmed_at, created_at, archived_at, unique_variant_id, bulk_variant_id, content_unit, package_size FROM items_with_variant
WHERE category_id = ? AND archived_at IS NULL
ORDER BY name
`

func (q *Queries) ListItemsInCategoryWithVariant(ctx context.Context, categoryID int64) ([]ItemsWithVariant, error) {
	rows, err := q.db.QueryContext(ctx, listItemsInCategoryWithVariant, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemsWithVariant{}
	for rows.Next() {
		var i ItemsWithVariant
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.CategoryID,
			&i.Notes,
			&i.PlacementConfirmedAt,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.UniqueVariantID,
			&i.BulkVariantID,
			&i.ContentUnit,
			&i.PackageSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsWithVariant = `-- name: ListItemsWithVariant :many
SELECT id, kind, name, category_id, notes, placement_confirmed_at, created_at, archived_at, unique_variant_id, bulk_variant_id, content_unit, package_size FROM items_with_variant
WHERE archived_at IS NULL
ORDER BY name
`

func (q *Queries) ListItemsWithVariant(ctx context.Context) ([]ItemsWithVariant, error) {
	rows, err := q.db.QueryContext(ctx, listItemsWithVariant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemsWithVariant{}
	for rows.Next() {
		var i ItemsWithVariant
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.CategoryID,
			&i.Notes,
			&i.PlacementConfirmedAt,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.UniqueVariantID,
			&i.BulkVariantID,
			&i.ContentUnit,
			&i.PackageSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnconfirmedItemsAtBranchCategories = `-- name: ListUnconfirmedItemsAtBranchCategories :many

SELECT
    i.id, i.name, i.category_id, c.name AS category_name,
    (SELECT count(*) FROM categories ch WHERE ch.parent_id = c.id AND ch.archived_at IS NULL) AS child_count
FROM items i
JOIN categories c ON c.id = i.category_id
WHERE i.archived_at IS NULL
  AND i.placement_confirmed_at IS NULL
  AND (SELECT count(*) FROM categories ch WHERE ch.parent_id = c.id AND ch.archived_at IS NULL) > 0
ORDER BY c.name, i.name
`

type ListUnconfirmedItemsAtBranchCategoriesRow struct {
	ID           int64
	Name         string
	CategoryID   int64
	CategoryName string
	ChildCount   int64
}

// D20's raw material: Items filed directly at a Category that has children, and
// whose placement has not been confirmed. The nudge fires only where a plausible
// sibling exists, which is why the child count matters.
func (q *Queries) ListUnconfirmedItemsAtBranchCategories(ctx context.Context) ([]ListUnconfirmedItemsAtBranchCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnconfirmedItemsAtBranchCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnconfirmedItemsAtBranchCategoriesRow{}
	for rows.Next() {
		var i ListUnconfirmedItemsAtBranchCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.CategoryName,
			&i.ChildCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
