// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: probe.sql

package probe

import (
	"context"
	"database/sql"
)

const attachBulkHolding = `-- name: AttachBulkHolding :exec
INSERT INTO bulk_holdings (holding_id, kind, quantity, unit_basis) VALUES (?, ?, ?, ?)
`

type AttachBulkHoldingParams struct {
	HoldingID int64
	Kind      string
	Quantity  int64
	UnitBasis string
}

func (q *Queries) AttachBulkHolding(ctx context.Context, arg AttachBulkHoldingParams) error {
	_, err := q.db.ExecContext(ctx, attachBulkHolding,
		arg.HoldingID,
		arg.Kind,
		arg.Quantity,
		arg.UnitBasis,
	)
	return err
}

const attachBulkItem = `-- name: AttachBulkItem :exec
INSERT INTO bulk_items (item_id, kind, content_unit, package_size) VALUES (?, ?, ?, ?)
`

type AttachBulkItemParams struct {
	ItemID      int64
	Kind        string
	ContentUnit string
	PackageSize sql.NullInt64
}

func (q *Queries) AttachBulkItem(ctx context.Context, arg AttachBulkItemParams) error {
	_, err := q.db.ExecContext(ctx, attachBulkItem,
		arg.ItemID,
		arg.Kind,
		arg.ContentUnit,
		arg.PackageSize,
	)
	return err
}

const attachCustodyPayload = `-- name: AttachCustodyPayload :exec
INSERT INTO ev_custody (event_id, type, to_custody, displaced_to_id) VALUES (?, ?, ?, ?)
`

type AttachCustodyPayloadParams struct {
	EventID       int64
	Type          string
	ToCustody     string
	DisplacedToID sql.NullInt64
}

func (q *Queries) AttachCustodyPayload(ctx context.Context, arg AttachCustodyPayloadParams) error {
	_, err := q.db.ExecContext(ctx, attachCustodyPayload,
		arg.EventID,
		arg.Type,
		arg.ToCustody,
		arg.DisplacedToID,
	)
	return err
}

const attachKindChangedPayload = `-- name: AttachKindChangedPayload :exec
INSERT INTO ev_kind_changed (event_id, type, from_kind, to_kind) VALUES (?, ?, ?, ?)
`

type AttachKindChangedPayloadParams struct {
	EventID  int64
	Type     string
	FromKind string
	ToKind   string
}

func (q *Queries) AttachKindChangedPayload(ctx context.Context, arg AttachKindChangedPayloadParams) error {
	_, err := q.db.ExecContext(ctx, attachKindChangedPayload,
		arg.EventID,
		arg.Type,
		arg.FromKind,
		arg.ToKind,
	)
	return err
}

const attachPlacementPayload = `-- name: AttachPlacementPayload :exec
INSERT INTO ev_placement (event_id, type, from_location_id, to_location_id) VALUES (?, ?, ?, ?)
`

type AttachPlacementPayloadParams struct {
	EventID        int64
	Type           string
	FromLocationID sql.NullInt64
	ToLocationID   int64
}

func (q *Queries) AttachPlacementPayload(ctx context.Context, arg AttachPlacementPayloadParams) error {
	_, err := q.db.ExecContext(ctx, attachPlacementPayload,
		arg.EventID,
		arg.Type,
		arg.FromLocationID,
		arg.ToLocationID,
	)
	return err
}

const attachPresencePayload = `-- name: AttachPresencePayload :exec
INSERT INTO ev_presence (event_id, type, present) VALUES (?, ?, ?)
`

type AttachPresencePayloadParams struct {
	EventID int64
	Type    string
	Present int64
}

func (q *Queries) AttachPresencePayload(ctx context.Context, arg AttachPresencePayloadParams) error {
	_, err := q.db.ExecContext(ctx, attachPresencePayload, arg.EventID, arg.Type, arg.Present)
	return err
}

const attachQuantityPayload = `-- name: AttachQuantityPayload :exec

INSERT INTO ev_quantity (event_id, type, delta, reason) VALUES (?, ?, ?, ?)
`

type AttachQuantityPayloadParams struct {
	EventID int64
	Type    string
	Delta   int64
	Reason  sql.NullString
}

// ------------------------------------------------- payload correspondence --
func (q *Queries) AttachQuantityPayload(ctx context.Context, arg AttachQuantityPayloadParams) error {
	_, err := q.db.ExecContext(ctx, attachQuantityPayload,
		arg.EventID,
		arg.Type,
		arg.Delta,
		arg.Reason,
	)
	return err
}

const attachUniqueHolding = `-- name: AttachUniqueHolding :exec
INSERT INTO unique_holdings (holding_id, kind, custody, custody_since, displaced_to_id)
VALUES (?, ?, ?, ?, ?)
`

type AttachUniqueHoldingParams struct {
	HoldingID     int64
	Kind          string
	Custody       string
	CustodySince  sql.NullString
	DisplacedToID sql.NullInt64
}

func (q *Queries) AttachUniqueHolding(ctx context.Context, arg AttachUniqueHoldingParams) error {
	_, err := q.db.ExecContext(ctx, attachUniqueHolding,
		arg.HoldingID,
		arg.Kind,
		arg.Custody,
		arg.CustodySince,
		arg.DisplacedToID,
	)
	return err
}

const attachUniqueItem = `-- name: AttachUniqueItem :exec

INSERT INTO unique_items (item_id, kind) VALUES (?, ?)
`

type AttachUniqueItemParams struct {
	ItemID int64
	Kind   string
}

// ------------------------------------------------- variant correspondence --
func (q *Queries) AttachUniqueItem(ctx context.Context, arg AttachUniqueItemParams) error {
	_, err := q.db.ExecContext(ctx, attachUniqueItem, arg.ItemID, arg.Kind)
	return err
}

const listEventIDs = `-- name: ListEventIDs :many
SELECT id FROM events ORDER BY id
`

func (q *Queries) ListEventIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listEventIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mutateEvent = `-- name: MutateEvent :exec

UPDATE events SET note = ? WHERE id = ?
`

type MutateEventParams struct {
	Note sql.NullString
	ID   int64
}

// ------------------------------------------------------ ledger mutability --
func (q *Queries) MutateEvent(ctx context.Context, arg MutateEventParams) error {
	_, err := q.db.ExecContext(ctx, mutateEvent, arg.Note, arg.ID)
	return err
}

const mutateQuantityPayload = `-- name: MutateQuantityPayload :exec
UPDATE ev_quantity SET delta = ? WHERE event_id = ?
`

type MutateQuantityPayloadParams struct {
	Delta   int64
	EventID int64
}

func (q *Queries) MutateQuantityPayload(ctx context.Context, arg MutateQuantityPayloadParams) error {
	_, err := q.db.ExecContext(ctx, mutateQuantityPayload, arg.Delta, arg.EventID)
	return err
}

const newCategory = `-- name: NewCategory :execlastid


INSERT INTO categories (name) VALUES (?)
`

// Queries that exist to be REJECTED by the schema.
//
// The production query set is designed to make violations inexpressible -- that
// is its job -- so it cannot prove the database rejects them. If InsertBulkItem
// hardcodes kind = 'Bulk', a test calling it proves the query file contains a
// literal, not that the composite foreign key exists.
//
// Every constrained value is therefore a PARAMETER here. sqlc types these from
// the schema without evaluating constraints, so rejection happens at runtime
// where the test wants it -- and a column rename breaks this package too.
//
// NEVER imported outside _test.go. scripts/archlint.sh enforces that.
// ---------------------------------------------------------------- fixtures --
func (q *Queries) NewCategory(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, newCategory, name)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const newEvent = `-- name: NewEvent :execlastid
INSERT INTO events (subject_kind, subject_id, type, occurred_at) VALUES (?, ?, ?, ?)
`

type NewEventParams struct {
	SubjectKind string
	SubjectID   int64
	Type        string
	OccurredAt  string
}

func (q *Queries) NewEvent(ctx context.Context, arg NewEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, newEvent,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Type,
		arg.OccurredAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const newHolding = `-- name: NewHolding :execlastid
INSERT INTO holdings (item_id, kind, stowed_location_id) VALUES (?, ?, ?)
`

type NewHoldingParams struct {
	ItemID           int64
	Kind             string
	StowedLocationID int64
}

func (q *Queries) NewHolding(ctx context.Context, arg NewHoldingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, newHolding, arg.ItemID, arg.Kind, arg.StowedLocationID)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const newItem = `-- name: NewItem :execlastid
INSERT INTO items (kind, name, category_id) VALUES (?, ?, ?)
`

type NewItemParams struct {
	Kind       string
	Name       string
	CategoryID int64
}

func (q *Queries) NewItem(ctx context.Context, arg NewItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, newItem, arg.Kind, arg.Name, arg.CategoryID)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const newLocation = `-- name: NewLocation :execlastid
INSERT INTO locations (name) VALUES (?)
`

func (q *Queries) NewLocation(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, newLocation, name)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const removeCategory = `-- name: RemoveCategory :exec

DELETE FROM categories WHERE id = ?
`

// ------------------------------------------------------ referential holds --
func (q *Queries) RemoveCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeCategory, id)
	return err
}

const removeEvent = `-- name: RemoveEvent :exec
DELETE FROM events WHERE id = ?
`

func (q *Queries) RemoveEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeEvent, id)
	return err
}

const removeLocation = `-- name: RemoveLocation :exec
DELETE FROM locations WHERE id = ?
`

func (q *Queries) RemoveLocation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeLocation, id)
	return err
}

const removeQuantityPayload = `-- name: RemoveQuantityPayload :exec
DELETE FROM ev_quantity WHERE event_id = ?
`

func (q *Queries) RemoveQuantityPayload(ctx context.Context, eventID int64) error {
	_, err := q.db.ExecContext(ctx, removeQuantityPayload, eventID)
	return err
}
