// Command sealedgen generates a registry of a sealed interface's variants by
// reading a package's AST for every type declaring the interface's unexported
// marker method.
//
// A hand-maintained list has a hole: add a variant, forget both the handler and
// the registry entry, and nothing fails. Deriving the list from the source
// closes it — the registry cannot go stale, because it is not maintained.
//
// It is one tool rather than one per union because the job does not differ: the
// event registry and the command registry are the same walk with different
// names, and a second copy of an AST walk is a second place for it to be wrong.
//
// Usage:
//
//	go run ./tools/sealedgen -dir internal/domain  -marker isEvent   -iface Event   -var AllEventTypes
//	go run ./tools/sealedgen -dir internal/command -marker isCommand -iface Command -var AllCommands
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	dir := flag.String("dir", "internal/domain", "package directory to scan")
	out := flag.String("out", "registry_gen.go", "output file, relative to -dir")
	marker := flag.String("marker", "isEvent", "the unexported method that seals the interface")
	iface := flag.String("iface", "Event", "the sealed interface's name")
	name := flag.String("var", "AllEventTypes", "the generated slice variable's name")
	flag.Parse()

	types, pkgName, err := sealedImplementors(*dir, *marker)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sealedgen: %v\n", err)
		os.Exit(1)
	}
	if len(types) == 0 {
		fmt.Fprintf(os.Stderr, "sealedgen: found no types implementing %s()\n", *marker)
		os.Exit(1)
	}

	src, err := render(pkgName, *iface, *name, types)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sealedgen: %v\n", err)
		os.Exit(1)
	}

	path := filepath.Join(*dir, *out)
	if err := os.WriteFile(path, src, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "sealedgen: write %s: %v\n", path, err)
		os.Exit(1)
	}
	fmt.Printf("sealedgen: %d %s variants -> %s\n", len(types), *iface, path)
}

// sealedImplementors returns every type in dir declaring a value-receiver method
// named marker, sorted for stable output.
func sealedImplementors(dir, marker string) (types []string, pkgName string, err error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		// Skip tests and generated output, so the registry never lists itself.
		return !strings.HasSuffix(fi.Name(), "_test.go") &&
			!strings.HasSuffix(fi.Name(), "_gen.go")
	}, 0)
	if err != nil {
		return nil, "", fmt.Errorf("parse %s: %w", dir, err)
	}

	seen := map[string]bool{}
	for name, pkg := range pkgs {
		pkgName = name
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				fn, ok := decl.(*ast.FuncDecl)
				if !ok || fn.Name.Name != marker || fn.Recv == nil || len(fn.Recv.List) != 1 {
					continue
				}
				// Only value receivers: a pointer receiver would mean the value
				// type does not satisfy the interface, which would be a bug.
				ident, ok := fn.Recv.List[0].Type.(*ast.Ident)
				if !ok {
					continue
				}
				if !seen[ident.Name] {
					seen[ident.Name] = true
					types = append(types, ident.Name)
				}
			}
		}
	}
	sort.Strings(types)
	return types, pkgName, nil
}

func render(pkgName, iface, name string, types []string) ([]byte, error) {
	var b bytes.Buffer

	fmt.Fprintf(&b, "// Code generated by tools/sealedgen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkgName)
	fmt.Fprintf(&b, `// %s lists every type implementing the sealed %s interface,
// derived from the source rather than maintained by hand.
//
// It is what makes exhaustiveness checkable: the tests walk this list and fail
// on any variant something has no case for. Because it is generated, adding a
// variant without handling it is a test failure rather than a silent gap.
`, name, iface)
	fmt.Fprintf(&b, "var %s = []%s{\n", name, iface)
	for _, t := range types {
		fmt.Fprintf(&b, "\t%s{},\n", t)
	}
	fmt.Fprintf(&b, "}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return src, nil
}
