// Code generated by tools/sealedgen. DO NOT EDIT.

package command

// AllCommands lists every type implementing the sealed Command interface,
// derived from the source rather than maintained by hand.
//
// It is what makes exhaustiveness checkable: the tests walk this list and fail
// on any variant something has no case for. Because it is generated, adding a
// variant without handling it is a test failure rather than a silent gap.
var AllCommands = []Command{
	ArchiveCategory{},
	ArchiveItem{},
	ArchiveLocation{},
	CheckOut{},
	Confirm{},
	Consume{},
	Count{},
	Demote{},
	Describe{},
	Discard{},
	Found{},
	Label{},
	MarkLost{},
	Move{},
	NewCategory{},
	NewHolding{},
	NewItem{},
	NewLocation{},
	Note{},
	Open{},
	Promote{},
	Receive{},
	Reclassify{},
	Rehome{},
	Rename{},
	ReparentCategory{},
	ReparentLocation{},
	RestoreCategory{},
	RestoreLocation{},
	Retire{},
	Return{},
	SetExpiry{},
	Snooze{},
	Verify{},
}
