// Command eventgen generates the event registry by reading the domain package's
// AST for every type that implements the sealed Event interface.
//
// A hand-maintained list has a hole: add a type, forget both the Fold case and
// the registry entry, and nothing fails. Deriving the list from the source
// closes it — the registry cannot go stale, because it is not maintained.
//
// Usage: go run ./tools/eventgen [-dir internal/domain] [-out registry_gen.go]
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// sealMethod is the unexported marker that makes Event a sealed interface.
const sealMethod = "isEvent"

func main() {
	dir := flag.String("dir", "internal/domain", "package directory to scan")
	out := flag.String("out", "registry_gen.go", "output file, relative to -dir")
	flag.Parse()

	types, pkgName, err := sealedImplementors(*dir, sealMethod)
	if err != nil {
		fmt.Fprintf(os.Stderr, "eventgen: %v\n", err)
		os.Exit(1)
	}
	if len(types) == 0 {
		fmt.Fprintf(os.Stderr, "eventgen: found no types implementing %s()\n", sealMethod)
		os.Exit(1)
	}

	src, err := render(pkgName, types)
	if err != nil {
		fmt.Fprintf(os.Stderr, "eventgen: %v\n", err)
		os.Exit(1)
	}

	path := filepath.Join(*dir, *out)
	if err := os.WriteFile(path, src, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "eventgen: write %s: %v\n", path, err)
		os.Exit(1)
	}
	fmt.Printf("eventgen: %d event types -> %s\n", len(types), path)
}

// sealedImplementors returns every type in dir declaring a value-receiver method
// named marker, sorted for stable output.
func sealedImplementors(dir, marker string) (types []string, pkgName string, err error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		// Skip tests and generated output, so the registry never lists itself.
		return !strings.HasSuffix(fi.Name(), "_test.go") &&
			!strings.HasSuffix(fi.Name(), "_gen.go")
	}, 0)
	if err != nil {
		return nil, "", fmt.Errorf("parse %s: %w", dir, err)
	}

	seen := map[string]bool{}
	for name, pkg := range pkgs {
		pkgName = name
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				fn, ok := decl.(*ast.FuncDecl)
				if !ok || fn.Name.Name != marker || fn.Recv == nil || len(fn.Recv.List) != 1 {
					continue
				}
				// Only value receivers: a pointer receiver would mean the value
				// type does not satisfy the interface, which would be a bug.
				ident, ok := fn.Recv.List[0].Type.(*ast.Ident)
				if !ok {
					continue
				}
				if !seen[ident.Name] {
					seen[ident.Name] = true
					types = append(types, ident.Name)
				}
			}
		}
	}
	sort.Strings(types)
	return types, pkgName, nil
}

func render(pkgName string, types []string) ([]byte, error) {
	var b bytes.Buffer

	fmt.Fprintf(&b, "// Code generated by tools/eventgen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkgName)
	fmt.Fprintf(&b, `// AllEventTypes lists every type implementing the sealed Event interface,
// derived from the source rather than maintained by hand.
//
// It is what makes exhaustiveness checkable: TestFoldHandlesEveryEventType
// walks this list and fails on any type Fold has no case for, and the same list
// drives the payload-persistence and formatter tests. Because it is generated,
// adding an event type without handling it is a test failure rather than a
// silent gap.
`)
	fmt.Fprintf(&b, "var AllEventTypes = []Event{\n")
	for _, t := range types {
		fmt.Fprintf(&b, "\t%s{},\n", t)
	}
	fmt.Fprintf(&b, "}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return src, nil
}
