// Code generated by tools/eventgen. DO NOT EDIT.

package domain

// AllEventTypes lists every type implementing the sealed Event interface,
// derived from the source rather than maintained by hand.
//
// It is what makes exhaustiveness checkable: TestFoldHandlesEveryEventType
// walks this list and fails on any type Fold has no case for, and the same list
// drives the payload-persistence and formatter tests. Because it is generated,
// adding an event type without handling it is a test failure rather than a
// silent gap.
var AllEventTypes = []Event{
	Acquired{},
	Adjusted{},
	CheckedOut{},
	Consumed{},
	Counted{},
	Discarded{},
	Found{},
	Gone{},
	HoldingCreated{},
	ItemKindChanged{},
	ItemPackageSizeChanged{},
	ItemUnitChanged{},
	MarkedLost{},
	Merged{},
	Moved{},
	NodeArchived{},
	NodeCreated{},
	NodeReparented{},
	NodeRestored{},
	Opened{},
	Rehomed{},
	Returned{},
	Split{},
	Verified{},
}
