// Code generated by tools/sealedgen. DO NOT EDIT.

package domain

// AllEventTypes lists every type implementing the sealed Event interface,
// derived from the source rather than maintained by hand.
//
// It is what makes exhaustiveness checkable: the tests walk this list and fail
// on any variant something has no case for. Because it is generated, adding a
// variant without handling it is a test failure rather than a silent gap.
var AllEventTypes = []Event{
	Acquired{},
	Adjusted{},
	CheckedOut{},
	Consumed{},
	Counted{},
	Discarded{},
	Found{},
	Gone{},
	HoldingCreated{},
	ItemPackageSizeChanged{},
	ItemUnitChanged{},
	MarkedLost{},
	Merged{},
	Moved{},
	NodeArchived{},
	NodeCreated{},
	NodeReparented{},
	NodeRestored{},
	Opened{},
	Rehomed{},
	Returned{},
	Split{},
	Verified{},
}
